#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090
# yt-x - Browse media from the terminal
# MIT License - Copyright (c) 2024-2026 Benexl

# ==============================================================================
# META
# ==============================================================================
CLI_NAME="${YT_X_NAME:-yt-x}"
CLI_APP_NAME="${YT_X_APP_NAME:-yt-x}"
CLI_VERSION="0.5.0"
CLI_AUTHOR="Benexl"
CLI_REPO_URL="https://github.com/Benexl/yt-x"
CLI_URL="https://raw.githubusercontent.com/Benexl/yt-x/refs/heads/master/yt-x"
CLI_SUPPORT_PROJECT_URL="https://buymeacoffee.com/benexl"
CLI_HEADER="\
██╗░░░██╗████████╗░░░░░░██╗░░██╗
╚██╗░██╔╝╚══██╔══╝░░░░░░╚██╗██╔╝
░╚████╔╝░░░░██║░░░█████╗░╚███╔╝░
░░╚██╔╝░░░░░██║░░░╚════╝░██╔██╗░
░░░██║░░░░░░██║░░░░░░░░░██╔╝╚██╗
░░░╚═╝░░░░░░╚═╝░░░░░░░░░╚═╝░░╚═╝"

# ==============================================================================
# SETUP
# ==============================================================================
_dep_ch() {
  command -v "$1" >/dev/null 2>&1
}

__init_env_platform() {
  CLI_DIR="$(dirname "$(realpath "$0")")"
  CLI_PATH="$CLI_DIR/$CLI_NAME"

  # If we are in Zsh, enable word splitting for the duration of the script
  if [ -n "$ZSH_VERSION" ]; then
    setopt shwordsplit
  fi

  # check if supports local
  if ! _dep_ch local; then
    # shellcheck disable=SC02329
    __local() {
      unset "$1"
      eval "$1=''"
    }
    # shellcheck disable=SC02329
    local() {
      __local "$1"
    }
  fi

  case "$(uname -a)" in
  *ndroid*) CLI_PLATFORM="android" ;;
  *Darwin*) CLI_PLATFORM="mac" ;;
  *MINGW* | *WSL2*) CLI_PLATFORM="windows" ;;
  *) CLI_PLATFORM="linux" ;;
  esac

  # Detect if terminal
  if [ -t 1 ]; then
    CLI_IS_TERMINAL=true
  else
    CLI_IS_TERMINAL=false
  fi

  # Detect if terminal supports true color
  if [ "$COLORTERM" = "truecolor" ] || [ "$COLORTERM" = "24bit" ]; then
    CLI_SUPPORTS_TRUE_COLOR=true
  else
    CLI_SUPPORTS_TRUE_COLOR=false
  fi

  # Detect correct mpv command (mpv or mpv.exe)
  if _dep_ch mpv; then
    MPV_CMD="mpv"
  elif _dep_ch "mpv.exe"; then
    MPV_CMD="mpv.exe"
  else
    MPV_CMD="mpv" # fallback
  fi

}

__init_env_paths() {

  XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
  XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
  XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

  # Directories
  CLI_CONFIG_DIR="$XDG_CONFIG_HOME/$CLI_APP_NAME"
  CLI_EXTENSIONS_DIR="$CLI_CONFIG_DIR/extensions"
  CLI_EXTENSIONS_SITES_DIR="$CLI_EXTENSIONS_DIR/sites"
  CLI_EXTENSIONS_THEMES_DIR="$CLI_EXTENSIONS_DIR/themes"
  CLI_EXTENSIONS_LANGS_DIR="$CLI_EXTENSIONS_DIR/langs"
  CLI_EXTENSIONS_CMDS_DIR="$CLI_EXTENSIONS_DIR/cmds"

  CLI_CACHE_DIR="$XDG_CACHE_HOME/$CLI_APP_NAME"
  CLI_STATE_DIR="$CLI_CACHE_DIR/state"
  CLI_PREVIEW_DIR="$CLI_CACHE_DIR/previews"
  CLI_PREVIEW_IMGS_DIR="$CLI_CACHE_DIR/previews/images"
  CLI_PREVIEW_TXT_DIR="$CLI_CACHE_DIR/previews/text"
  CLI_PLAYLIST_DIR="$CLI_CACHE_DIR/playlists"
  CLI_ARCHIVE_DIR="$CLI_CACHE_DIR/archives"
  CLI_LOG_DIR="$CLI_CACHE_DIR/logs"

  # Files
  CLI_CONFIG_FILE="$CLI_CONFIG_DIR/config.sh"
  CLI_DEFAULT_THEME_FILE="$CLI_EXTENSIONS_THEMES_DIR/default.theme"
  CLI_DEFAULT_LANG_FILE="$CLI_EXTENSIONS_LANGS_DIR/default.lang"
  CLI_RECENT_FILE="$CLI_CONFIG_DIR/recent.json"
  CLI_SAVED_FILE="$CLI_CONFIG_DIR/saved_videos.json"
  CLI_CUSTOM_PLAYLISTS_FILE="$CLI_CONFIG_DIR/custom_playlists.json"
  CLI_SUBSCRIPTIONS_FILE="$CLI_CONFIG_DIR/subscriptions.json"
  CLI_CUSTOM_CMDS_FILE="$CLI_CONFIG_DIR/custom_cmds.json"

  CLI_STATE_FILE="$CLI_STATE_DIR/$(date +%Y-%m-%d_%H-%M-%S).json"
  CLI_LOG_FILE="$CLI_CACHE_DIR/logs/${CLI_NAME}.log"
  CLI_SEARCH_HISTORY_FILE="$CLI_CACHE_DIR/search_history.txt"
  CLI_LOG_FILE="$CLI_LOG_DIR/${CLI_NAME}.log"

  # Ensure directories exist
  mkdir -p \
    "$CLI_EXTENSIONS_SITES_DIR" \
    "$CLI_EXTENSIONS_THEMES_DIR" \
    "$CLI_EXTENSIONS_LANGS_DIR" \
    "$CLI_EXTENSIONS_CMDS_DIR" \
    "$CLI_STATE_DIR" \
    "$CLI_PREVIEW_IMGS_DIR" \
    "$CLI_PREVIEW_TXT_DIR" \
    "$CLI_PLAYLIST_DIR" \
    "$CLI_ARCHIVE_DIR" \
    "$CLI_LOG_DIR"

}

__post_init_env() {
  export SHELL="sh"

}

_init_env() {
  __init_env_platform
  __init_env_paths
  __post_init_env
}

# ==============================================================================
# CONFIGURATION & ENVIRONMENT
# ==============================================================================
__load_default_config() {
  : "${CONFIG_AUTOLOADED_EXTENSIONS:=}"
  : "${CONFIG_ENABLE_COLORS:=true}"
  : "${CONFIG_LAUNCHER:=fzf}"
  : "${CONFIG_ENABLE_PREVIEW:=false}"
  : "${CONFIG_IMAGE_RENDERER:=chafa}"
  : "${CONFIG_CHAFA_ARGS:=}"
  : "${CONFIG_ICAT_ARGS:=}"
  : "${CONFIG_IMGCAT_ARGS:=}"
  : "${CONFIG_YT_DLP_ARGS:=}"
  : "${CONFIG_PLAYER:=mpv}"
  : "${CONFIG_DISOWN_STREAMING_PROCESS:=false}"
  : "${CONFIG_DISOWN_DOWNLOADING_PROCESS:=false}"
  : "${CONFIG_MPV_ARGS:=}"
  : "${CONFIG_VLC_ARGS:=}"
  : "${CONFIG_TPLAY_ARGS:=}"
  : "${CONFIG_VIDEO_QUALITY:=1080}"
  : "${CONFIG_PER_PAGE:=30}"
  : "${CONFIG_BROWSER:=}"
  : "${CONFIG_EDITOR:=${EDITOR:-vi}}"
  : "${CONFIG_NOTIFICATION_DURATION:=5}"
  : "${CONFIG_DOWNLOAD_DIR:=$HOME/Videos/$CLI_NAME}"
  : "${CONFIG_CHECK_FOR_UPDATES:=true}"
  : "${CONFIG_NO_OF_RECENT:=10}"
  : "${CONFIG_ENABLE_SEARCH_HISTORY:=true}"
  : "${CONFIG_ROFI_THEME:=}"
  : "${CONFIG_FZF_OPTS:="
  --ansi
  --border
  --scheme=history
  --style=full
  --color=bg+:#283457
  --color=bg:#16161e
  --color=border:#27a1b9
  --color=fg:#c0caf5
  --color=gutter:#16161e
  --color=header:#ff9e64
  --color=hl+:#2ac3de
  --color=hl:#2ac3de
  --color=info:#545c7e
  --color=marker:#ff007c
  --color=pointer:#ff007c
  --color=prompt:#2ac3de
  --color=query:#c0caf5:regular
  --color=scrollbar:#27a1b9
  --color=separator:#ff9e64
  --color=spinner:#ff007c
  --border=rounded
  --border-label=''
  --prompt=' >'
  --marker=' >'
  --pointer='◆'
  --layout=reverse
  --cycle
  --ghost='こんにちは...'
  --height=100%
  --bind=right:accept,left:abort,ctrl-/:toggle-preview,ctrl-space:toggle-wrap+toggle-preview-wrap
  --no-margin
  +m
  -i
  --exact
  --tabstop=1
  --preview-window=border-rounded,left,35%,wrap
  --wrap
"}"
}

__load_env_config() {
  CONFIG_AUTOLOADED_EXTENSIONS="${YT_X_AUTOLOADED_EXTENSIONS:-$CONFIG_AUTOLOADED_EXTENSIONS}"
  CONFIG_ENABLE_COLORS="${YT_X_ENABLE_COLORS:-$CONFIG_PRETTY_PRINT}"
  CONFIG_SELECTOR="${YT_X_SELECTOR:-$CONFIG_SELECTOR}"
  CONFIG_ENABLE_PREVIEW="${YT_X_ENABLE_PREVIEW:-$CONFIG_ENABLE_PREVIEW}"

  # Renderer Settings
  CONFIG_IMAGE_RENDERER="${YT_X_IMAGE_RENDERER:-$CONFIG_IMAGE_RENDERER}"
  CONFIG_CHAFA_ARGS="${YT_X_CHAFA_ARGS:-$CONFIG_CHAFA_ARGS}"
  CONFIG_ICAT_ARGS="${YT_X_ICAT_ARGS:-$CONFIG_ICAT_ARGS}"
  CONFIG_IMGCAT_ARGS="${YT_X_IMGCAT_ARGS:-$CONFIG_IMGCAT_ARGS}"

  # Player Settings
  CONFIG_PLAYER="${YT_X_PLAYER:-$CONFIG_PLAYER}"
  CONFIG_MPV_ARGS="${YT_X_MPV_ARGS:-$CONFIG_MPV_ARGS}"
  CONFIG_VLC_ARGS="${YT_X_VLC_ARGS:-$CONFIG_VLC_ARGS}"
  CONFIG_TPLAY_ARGS="${YT_X_TPLAY_ARGS:-$CONFIG_TPLAY_ARGS}"

  # Media Prefs
  CONFIG_VIDEO_QUALITY="${YT_X_VIDEO_QUALITY:-$CONFIG_VIDEO_QUALITY}"
  CONFIG_PER_PAGE="${YT_X_PER_PAGE:-$CONFIG_PER_PAGE}"
  CONFIG_BROWSER="${YT_X_BROWSER:-$CONFIG_BROWSER}"

  # System/UI
  CONFIG_EDITOR="${YT_X_EDITOR:-$CONFIG_EDITOR}"
  CONFIG_NOTIFICATION_DURATION="${YT_X_NOTIFICATION_DURATION:-$CONFIG_NOTIFICATION_DURATION}"
  CONFIG_DOWNLOAD_DIR="${YT_X_DOWNLOAD_DIR:-$CONFIG_DOWNLOAD_DIR}"
  CONFIG_CHECK_FOR_UPDATES="${YT_X_CHECK_FOR_UPDATES:-$CONFIG_CHECK_FOR_UPDATES}"
  CONFIG_NO_OF_RECENT="${YT_X_NO_OF_RECENT:-$CONFIG_NO_OF_RECENT}"
  CONFIG_ENABLE_SEARCH_HISTORY="${YT_X_ENABLE_SEARCH_HISTORY:-$CONFIG_ENABLE_SEARCH_HISTORY}"

  # Advanced
  CONFIG_FZF_OPTS="${YT_X_FZF_OPTS:-$CONFIG_FZF_OPTS}"
  CONFIG_ROFI_THEME_MAIN="${YT_X_ROFI_THEME_MAIN:-$CONFIG_ROFI_THEME_MAIN}"
  CONFIG_ROFI_THEME_PREVIEW="${YT_X_ROFI_THEME_PREVIEW:-$CONFIG_ROFI_THEME_PREVIEW}"
  CONFIG_ROFI_THEME_PROMPT="${YT_X_ROFI_THEME_PROMPT:-$CONFIG_ROFI_THEME_PROMPT}"
  CONFIG_ROFI_THEME_CONFIRM="${CONFIG_ROFI_THEME_CONFIRM:-$CONFIG_ROFI_THEME_CONFIRM}"
}

__load_default_lang() {

  # ==============================================================================
  # MENUS
  # ==============================================================================

  # core: navigation
  TXT_MENU_NEXT="Next"
  TXT_MENU_PREVIOUS="Previous"
  TXT_MENU_BACK="Back"
  TXT_MENU_EXIT="Exit"

  # core: others
  TXT_MENU_INVALID_ACTION="Invalid Action"

  # main
  TXT_MENU_MAIN="Main Menu"
  TXT_MENU_MAIN_FEED="Your Feed"
  TXT_MENU_MAIN_TRENDING="Trending"
  TXT_MENU_MAIN_PLAYLISTS="Playlists"
  TXT_MENU_MAIN_SEARCH="Search"
  TXT_MENU_MAIN_WATCH_LATER="Watch Later"
  TXT_MENU_MAIN_SUBS_FEED="Subscription Feed"
  TXT_MENU_MAIN_CHANNELS="Channels"
  TXT_MENU_MAIN_CUSTOM_PLAYLISTS="Custom Playlists"
  TXT_MENU_MAIN_LIKED="Liked Videos"
  TXT_MENU_MAIN_SAVED="Saved Videos"
  TXT_MENU_MAIN_HISTORY="Watch History"
  TXT_MENU_MAIN_RECENT="Recent"
  TXT_MENU_MAIN_CLIPS="Clips"
  TXT_MENU_MAIN_EDIT_CONFIG="Edit Config"
  TXT_MENU_MAIN_MISC="Miscellaneous"
  # miscellaneous
  TXT_MENU_MISC_EXPLORE_CHANNELS="Explore Channels"
  TXT_MENU_MISC_EXPLORE_PLAYLISTS="Explore Playlists"
  TXT_MENU_MISC_SEARCH_HISTORY="Search History"
  TXT_MENU_MISC_NEW_CUSTOM_CMD="New Custom Command"
  TXT_MENU_MISC_CUSTOM_CMDS="Custom Commands"
  TXT_MENU_MISC_EDIT_SEARCH_HISTORY="Edit Search History"
  TXT_MENU_MISC_EDIT_CUSTOM_PLAYLISTS="Edit Custom Playlists"
  TXT_MENU_MISC_EDIT_MPV_CONFIG="Edit MPV Config"
  TXT_MENU_MISC_EDIT_YTDLP_CONFIG="Edit yt-dlp Config"
  TXT_MENU_MISC_EDIT_CUSTOM_CMDS="Edit Custom Commands"
  TXT_MENU_MISC_SYNC_SUBS="Sync YouTube Subscriptions"
  TXT_MENU_MISC_CLEAR_SEARCH_HISTORY="Clear Search History"

  # channel actions
  TXT_MENU_CHANNEL_VIDEOS="Videos"
  TXT_MENU_CHANNEL_FEATURED="Featured"
  TXT_MENU_CHANNEL_SEARCH="Search"
  TXT_MENU_CHANNEL_PLAYLISTS="Playlists"
  TXT_MENU_CHANNEL_SHORTS="Shorts"
  TXT_MENU_CHANNEL_STREAMS="Streams"
  TXT_MENU_CHANNEL_PODCASTS="Podcasts"
  TXT_MENU_CHANNEL_SUBSCRIBE="Subscribe"
  TXT_MENU_CHANNEL_BACK="Back"
  TXT_MENU_CHANNEL_EXIT="Exit"

  # playlist explorer
  TXT_MENU_PLAYLIST_EXPLORER_PROMPT="Select Media"

  # Playlist actions
  TXT_MENU_PLAYLIST_ACTIONS_PROMPT="Select Media Action"
  TXT_MENU_PLAYLIST_ACTIONS_WATCH="Watch"
  TXT_MENU_PLAYLIST_ACTIONS_PLAY_ALL="Play All"
  TXT_MENU_PLAYLIST_ACTIONS_LISTEN="Listen"
  TXT_MENU_PLAYLIST_ACTIONS_LISTEN_ALL="Listen To All"
  TXT_MENU_PLAYLIST_ACTIONS_MIX="Mix"
  TXT_MENU_PLAYLIST_ACTIONS_SAVE="Save"
  TXT_MENU_PLAYLIST_ACTIONS_UNSAVE="UnSave"
  TXT_MENU_PLAYLIST_ACTIONS_SAVE_PLAYLIST="Save Playlist"
  TXT_MENU_PLAYLIST_ACTIONS_SUBSCRIBE="Subscribe To Channel"
  TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD="Download"
  TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL="Download All"
  TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_AUDIO="Download (Audio Only)"
  TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL_AUDIO="Download All (Audio Only)"
  TXT_MENU_PLAYLIST_ACTIONS_BROWSER="Open in Browser"
  TXT_MENU_PLAYLIST_ACTIONS_TOGGLE_ENUM="Toggle Enumerate Downloads"
  TXT_MENU_PLAYLIST_ACTIONS_SHELL="Shell"

  [ -s "$CLI_DEFAULT_LANG_FILE" ] && . "$CLI_DEFAULT_LANG_FILE"

}

__load_default_theme() {
  if $CLI_SUPPORTS_TRUE_COLOR && $CONFIG_ENABLE_COLORS; then
    THEME_FZF_ICON_COLOR_PRIMARY=""
    THEME_FZF_ICON_COLOR_SECONDARY=""
    THEME_FZF_ICON_COLOR_ACCENT=""
    THEME_FZF_ICON_COLOR_ERROR=""

    [ -s "$CLI_DEFAULT_THEME_FILE" ] && . "$CLI_DEFAULT_THEME_FILE"
  fi
}

__post_config_load() {
  if [ -n "$CONFIG_AUTOLOADED_EXTENSIONS" ]; then
    for ext in $(echo "$CONFIG_AUTOLOADED_EXTENSIONS" | tr ',' '\n'); do
      [ -s "$CLI_EXTENSIONS_DIR/$ext" ] && . "$CLI_EXTENSIONS_DIR/$ext"
    done
  fi

  export FZF_DEFAULT_OPTS="$CONFIG_FZF_OPTS"
}

_print_config() {
  cat <<EOF
#
# ===================================================================================
#
#     ██╗░░░██╗████████╗░░░░░░██╗░░██╗  ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░
#     ╚██╗░██╔╝╚══██╔══╝░░░░░░╚██╗██╔╝  ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░
#     ░╚████╔╝░░░░██║░░░█████╗░╚███╔╝░  ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░
#     ░░╚██╔╝░░░░░██║░░░╚════╝░██╔██╗░  ██║░░██╗██║░░██╗██║╚████║██╔══╝░░██║██║░░╚██╗
#     ░░░██║░░░░░░██║░░░░░░░░░██╔╝╚██╗  ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝
#     ░░░╚═╝░░░░░░╚═╝░░░░░░░░░╚═╝░░╚═╝  ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░
#
# ===================================================================================
#
# !! BE CAREFUL WHAT YOU INCLUDE HERE SINCE THE CONFIG FILE IS SOURCED AS A SCRIPT  !!
# !! ITS RECOMMENDED TO ONLY DO VARIABLE ASSIGNMENTS AND CONDITIONAL ASSIGNMENTS    !!
# !! AND DO MORE COMPLEX STUFF USING EXTENSIONS BY CONVENTION                       !!
# !! Environment variables (export YT_X_VAR=...) override these settings.           !!
#
# ===================================================================================

# List of extensions to load automatically on startup
CONFIG_AUTOLOADED_EXTENSIONS="$CONFIG_AUTOLOADED_EXTENSIONS"

# Enable or disable colored/formatted output
# Options: true, false (Default: true)
CONFIG_ENABLE_COLORS="$CONFIG_ENABLE_COLORS"

# The menu launcher tool used for the ui
# Options: fzf, rofi (Default: fzf)
CONFIG_LAUNCHER="$CONFIG_LAUNCHER"

# Enable image/video previews within the selector
# Options: true, false (Default: false)
CONFIG_ENABLE_PREVIEW="$CONFIG_ENABLE_PREVIEW"

# The tool used to render previews in the terminal
# Options: chafa, icat, imgcat (Default: chafa)
CONFIG_IMAGE_RENDERER="$CONFIG_IMAGE_RENDERER"

# Extra arguments for specific image renderers
CONFIG_CHAFA_ARGS="$CONFIG_CHAFA_ARGS"
CONFIG_ICAT_ARGS="$CONFIG_ICAT_ARGS"
CONFIG_IMGCAT_ARGS="$CONFIG_IMGCAT_ARGS"

# custom args for yt-dlp
CONFIG_YT_DLP_ARGS="$CONFIG_YT_DLP_ARGS"

# The media player used for playback
# Options: mpv, vlc, tplay (Default: mpv)
CONFIG_PLAYER="$CONFIG_PLAYER"

# Extra arguments for specific media players
CONFIG_MPV_ARGS="$CONFIG_MPV_ARGS"
CONFIG_VLC_ARGS="$CONFIG_VLC_ARGS"
CONFIG_TPLAY_ARGS="$CONFIG_TPLAY_ARGS"

# Preferred video resolution
# Options: 2160, 1440, 1080, 720, 480 (Default: 1080)
CONFIG_VIDEO_QUALITY="$CONFIG_VIDEO_QUALITY"

# Whether to disown the streaming/downloading process to prevent blocking the UI
# options: true, false (Default: false)
CONFIG_DISOWN_STREAMING_PROCESS="$CONFIG_DISOWN_STREAMING_PROCESS"
CONFIG_DISOWN_DOWNLOADING_PROCESS="$CONFIG_DISOWN_DOWNLOADING_PROCESS"

# Maximum number of search results to fetch per page
# Options: Integer (Default: 30)
CONFIG_PER_PAGE="$CONFIG_PER_PAGE"

# Browser for yt-dlp to get cookies from
# passed to --cookies-from-browser yt-dlp option
# Currently supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi, whale
# NOTE: this option is entirely dependent on what yt-dlp supports
CONFIG_BROWSER="$CONFIG_BROWSER"

# Text editor for manual configuration/metadata editing
# Options: vim, nano, code ... (Default: \$EDITOR or vi)
CONFIG_EDITOR="$CONFIG_EDITOR"

# Duration in seconds for desktop notifications
CONFIG_NOTIFICATION_DURATION="$CONFIG_NOTIFICATION_DURATION"

# Directory where downloads are saved
# Default: $HOME/Videos/$CLI_NAME
CONFIG_DOWNLOAD_DIR="$CONFIG_DOWNLOAD_DIR"

# Automatically check for script updates on startup
# Options: true, false (Default: true)
CONFIG_CHECK_FOR_UPDATES="$CONFIG_CHECK_FOR_UPDATES"

# Number of items to keep in the recent history
CONFIG_NO_OF_RECENT="$CONFIG_NO_OF_RECENT"

# Enable or disable saving search queries to history
# Options: true, false (Default: true)
CONFIG_ENABLE_SEARCH_HISTORY="$CONFIG_ENABLE_SEARCH_HISTORY"

# Custom options passed directly to fzf
CONFIG_FZF_OPTS="$CONFIG_FZF_OPTS"

# Rofi config
CONFIG_ROFI_THEME_MAIN="$CONFIG_ROFI_THEME_MAIN"
CONFIG_ROFI_THEME_PREVIEW="$CONFIG_ROFI_THEME_PREVIEW"
CONFIG_ROFI_THEME_PROMPT="$CONFIG_ROFI_THEME_PROMPT"
CONFIG_ROFI_THEME_CONFIRM="$CONFIG_ROFI_THEME_CONFIRM"
EOF
}

_load_config() {
  __load_default_config

  # Create config if missing
  [ -f "$CLI_CONFIG_FILE" ] || _print_config >"$CLI_CONFIG_FILE"

  # Load Config File
  . "$CLI_CONFIG_FILE"

  __load_env_config
  __load_default_lang
  __load_default_theme
  __post_config_load
}

# ==============================================================================
# CORE: utilities
# ==============================================================================
_util_byebye() {
  clear
  _ui_notify "Have a good day $USER"
  exit "${1:-0}"
}

_util_generate_hash() {
  local input

  # Check if input is passed as an argument or piped
  if [ -n "$1" ]; then
    input="$1"
  else
    input=$(cat)
  fi

  if _dep_ch sha256sum; then
    printf "%s" "$input" | sha256sum | awk '{print $1}'
  elif _dep_ch shasum; then
    printf "%s" "$input" | shasum -a 256 | awk '{print $1}'
  elif _dep_ch sha256; then
    printf "%s" "$input" | sha256 | awk '{print $1}'
  elif _dep_ch openssl; then
    printf "%s" "$input" | openssl dgst -sha256 | awk '{print $2}'
  else
    # fallback
    printf "%s" "$input" | base64 | tr '/+' '_-' | tr -d '\n'
  fi
}

# ==============================================================================
# CORE UI: notify
# ==============================================================================
__ui_notify_terminal() {
  #TODO: finish implementation
  case "$1" in
  info) echo "$2" >&2 && sleep "$NOTIFICATION_DURATION" ;;
  warning) echo "$2" >&2 && sleep "$NOTIFICATION_DURATION" ;;
  error) echo "$2" >&2 && sleep "$NOTIFICATION_DURATION" ;;
  critical) echo "$2" >&2 && exit 1 ;;
  *) echo "$2" >&2 && sleep "$NOTIFICATION_DURATION" ;;
  esac

}

__ui_notify_non_terminal() {
  #TODO: finish implementation
  case "$1" in
  info) notify-send "$2" ;;
  warning) notify-send "$2" ;;
  error) notify-send "$2" ;;
  critical) notify-send "$2" && exit 1 ;;
  esac
}

_ui_notify() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal info "$1"
  else
    __ui_notify_non_terminal info "$1"
  fi
}

_ui_notify_warning() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal warning "$1"
  else
    __ui_notify_non_terminal warning "$1"
  fi
}

_ui_notify_error() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal error "$1"
  else
    __ui_notify_non_terminal error "$1"
  fi
}

_ui_notify_critical() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal critical "$1"
  else
    __ui_notify_non_terminal critical "$1"
  fi
}

ui_notify() {
  _ui_notify "$@"
}

ui_notify_warning() {
  _ui_notify_warning "$@"
}

ui_notify_error() {
  _ui_notify_error "$@"
}

ui_notify_critical() {
  _ui_notify_critical "$@"
}

# ==============================================================================
# CORE UI: launcher
# ==============================================================================
__ui_fzf_launcher() {

  fzf \
    --info=hidden \
    --layout=reverse \
    --height=100% \
    --prompt="${1}: " \
    --header-first --header="$CLI_HEADER" \
    --exact --cycle --ansi
}

__ui_rofi_launcher() {
  local theme
  local selection

  [ -s "$CONFIG_ROFI_THEME_MAIN" ] && theme="-theme $CONFIG_ROFI_THEME_MAIN"
  # shellcheck disable=SC2086
  selection=$(while read -r line; do echo "$line" | sed -r 's/\x1B(\[[0-9;]*[a-zA-Z]|\(B)//g'; done | rofi -no-config $theme -sort -matching fuzzy -dmenu -i -width 1500 -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf)
  [ -z "$selection" ] && echo "Exit" || echo "$selection"
}

_ui_launcher() {
  case "$CONFIG_SELECTOR" in
  rofi) __ui_rofi_launcher "$@" ;;
  fzf) __ui_fzf_launcher "$@" ;;
  esac

}

ui_launcher() {
  _ui_launcher "$@"
}

# ==============================================================================
# CORE UI: launcher with preview
# ==============================================================================
__ui_fzf_launcher_with_preview() {
  fzf \
    --info=hidden \
    --layout=reverse \
    --height=100% \
    --prompt="${1}: " \
    --header-first --header="$CLI_HEADER" \
    --preview-window=left,35%,wrap --bind=right:accept \
    --expect=shift-left,shift-right --tabstop=1 \
    --cycle --exact \
    --ansi --preview="YT_X_MINIMAL_ENV=true $CLI_PATH _internal_fzf_preview $2 {}"
}

__ui_rofi_launcher_with_preview() {
  local theme
  local selection

  [ -z "$CONFIG_ROFI_THEME_PREVIEW" ] && theme="-theme $CONFIG_ROFI_THEME_PREVIEW"
  selection=$(while read -r line; do echo "$line" | sed -r 's/\x1B(\[[0-9;]*[a-zA-Z]|\(B)//g'; done | rofi -no-config -theme "$CONFIG_ROFI_THEME_PREVIEW" -sort -matching fuzzy -dmenu -i -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf)
  [ -z "$selection" ] && echo "Exit" || echo "$selection"
}

_ui_launcher_with_preview() {
  case "$PREFERRED_SELECTOR" in
  rofi) __ui_rofi_launcher_with_preview "$@" ;;
  fzf) __ui_fzf_launcher_with_preview "$@" ;;
  esac

}

ui_launcher_with_preview() {
  _ui_launcher_with_preview "$@"
}

# ==============================================================================
# CORE UI: prompt
# ==============================================================================
__ui_default_prompt() {
  if _dep_ch gum; then
    gum input --header "$CLI_HEADER" --prompt "$1: " --value "$2"
  else
    printf "%s\n" "$CLI_HEADER" >/dev/stderr
    printf "%s: " "$1" >/dev/stderr
    read -r VAL
    printf "%s" "$VAL"
  fi
}

__ui_rofi_prompt() {
  local theme

  [ -s "$CONFIG_ROFI_THEME_PROMPT" ] && theme="-theme $CONFIG_ROFI_THEME_PROMPT"

  # shellcheck disable=SC2086
  rofi -dmenu $theme -p "$1: "
}

_ui_prompt() {
  #TODO: implement defaults
  case "$CONFIG_SELECTOR" in
  rofi) __ui_rofi_prompt "$@" ;;
  *) __ui_default_prompt "$@" ;;
  esac
}

ui_prompt() {
  _ui_prompt "$@"
}

# ==============================================================================
# CORE UI: confirm
# ==============================================================================
_ui_default_confirm() {
  if _dep_ch gum; then
    gum confirm "$1"
  else
    printf "%s\n" "$CLI_HEADER" >/dev/stderr
    printf "%s [y/N]: " "$1" >/dev/stderr
    read -r CONFIRMED
    case "$CONFIRMED" in
    y | Y)
      return 0
      ;;
    *)
      return 1
      ;;
    esac
  fi
}

_ui_rofi_confirm() {
  local theme

  [ -s "$CONFIG_ROFI_THEME_PROMPT" ] && theme="-theme $CONFIG_ROFI_THEME_CONFIRM"

  # shellcheck disable=SC2086
  rofi -dmenu $theme -p "$1: "
}

_ui_confirm() {
  #TODO: implement defaults
  case "$CONFIG_SELECTOR" in
  rofi) _ui_rofi_confirm "$@" ;;
  *) _ui_default_confirm "$@" ;;
  esac
}

ui_confirm() {
  _ui_confirm "$@"
}

# ==============================================================================
# CORE UI: pager
# ==============================================================================
__ui_default_pager() {
  if _dep_ch bat; then
    bat --paging=always --theme=TwoDark --color=always
  elif _dep_ch gum; then
    gum pager
  elif _dep_ch less; then
    less -R
  else
    more
  fi
}

__ui_rofi_pager() {
  local theme

  [ -s "$CONFIG_ROFI_THEME_MAIN" ] && theme="-theme $CONFIG_ROFI_THEME_MAIN"

  # shellcheck disable=SC2086
  rofi -no-config $theme -sort -matching fuzzy -dmenu -i -width 1500 -p "" -mesg "Preview" -matching fuzzy -sorting-method fzf
}

_ui_pager() {
  case "$CONFIG_LAUNCHER" in
  rofi) __ui_rofi_pager ;;
  *) __ui_default_pager ;;
  esac
}

ui_pager() {
  _ui_pager
}

# ==============================================================================
# Previews
# ==============================================================================
generate_text_preview() {
  [ -z "$search_results" ] && return 1
  ids="$(echo "$1" | jq '.entries[].id' -r 2>/dev/null)"

  lines="$(echo "$ids" | wc -l)"
  for i in $(seq 1 "$lines"); do
    video=$(echo "$1" | jq ".entries[$((i - 1))]")
    title=$(echo "$video" | jq ".title" -r | sed 's/"/\\\\"/g;s/%/%%/g;s/\$/\\\\$/g;s/^.. //g')
    id=$(echo "$video" | jq '.id' -r)
    preview_image=$(echo "$video" | jq '.thumbnails[-1].url' -r | generate_sha256)

    view_count=$(
      echo "$video" | jq -r '
      .view_count
      |tostring
      |split("")
      |reverse
      |join("")
      |gsub("(?<thousands>[0-9]{3})(?=[0-9])"; "\(.thousands),")
      |split("")
      |reverse
      |join("")
      '
    )

    live_status=$(echo "$video" | jq '.live_status' -r)
    [ "$live_status" = "is_live" ] && live_status='Online'
    [ "$live_status" = "was_live" ] && live_status='Offline'
    [ "$live_status" = "null" ] && live_status='False'

    description=$(echo "$video" | jq '.description' -r | sed "s/\"//g;s/%//g")
    channel=$(echo "$video" | jq '.channel' -r)

    # some duration calculations
    duration=$(echo "$video" | jq '
    try 
      if .duration>=3600 then
        if .duration/3600|floor == 1 then 
          .duration/3600|floor|tostring + " hour" 
        else 
          .duration/3600|floor|tostring + " hours" 
        end 
      elif .duration>=60 then
        if .duration/60|floor == 1 then 
          .duration/60|floor|tostring + " min" 
        else 
          .duration/60|floor|tostring + " mins" 
        end 
      else 
        if .duration == 1 then 
          .duration/1|floor|tostring + " sec" 
        else 
          .duration/1|floor|tostring + " secs" 
        end 
      end
    catch
      "Unknown" 
    ' -r)

    # some date calculations
    timestamp=$(echo "$video" | jq '.timestamp' -r)
    relative_timestamp=$((CURRENT_TIME - timestamp))
    if [ "$relative_timestamp" -lt 60 ]; then
      timestamp="just now"
    elif [ "$relative_timestamp" -lt 3600 ]; then
      timestamp=$((relative_timestamp / 60))
      if [ "$timestamp" -eq 1 ]; then
        timestamp="$timestamp minute ago"
      else
        timestamp="$timestamp minutes ago"
      fi
    elif [ "$relative_timestamp" -lt 86400 ]; then
      timestamp=$((relative_timestamp / 3600))
      if [ "$relative_timestamp" -lt 7200 ]; then
        timestamp="1 hour ago"
      else
        timestamp=$((relative_timestamp / 3600))
        timestamp="$timestamp hours ago"
      fi
    elif [ "$relative_timestamp" -lt 604800 ]; then
      timestamp=$((relative_timestamp / 86400))
      if [ "$timestamp" -eq 1 ]; then
        timestamp="$timestamp day ago"
      else
        timestamp="$timestamp days ago"
      fi
    elif [ "$relative_timestamp" -lt 2635200 ]; then
      timestamp=$((relative_timestamp / 604800))
      if [ "$timestamp" -eq 1 ]; then
        timestamp="$timestamp week ago"
      else
        timestamp="$timestamp weeks ago"
      fi
    elif [ "$relative_timestamp" -lt 31622400 ]; then
      timestamp=$((relative_timestamp / 2635200))
      if [ "$timestamp" -eq 1 ]; then
        timestamp="$timestamp month ago"
      else
        timestamp="$timestamp months ago"
      fi
    else
      timestamp=$((relative_timestamp / 31622400))
      if [ "$timestamp" -eq 1 ]; then
        timestamp="$timestamp year ago"
      else
        timestamp="$timestamp years ago"
      fi
    fi

    printf "

if [ -f \"$CLI_PREVIEW_IMAGES_CACHE_DIR/${preview_image}.jpg\" ];then fzf_preview \"$CLI_PREVIEW_IMAGES_CACHE_DIR/${preview_image}.jpg\" 2>/dev/null;
else echo loading preview image...;
fi
ll=1
while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
echo

echo \"$title\"

ll=1
while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
printf \"${MAGENTA}${BOLD}Channel: ${RESET}$channel\n\";
printf \"${MAGENTA}${BOLD}Duration: ${RESET}$duration\n\";
printf \"${MAGENTA}${BOLD}View Count: ${RESET}$view_count views\n\";
printf \"${MAGENTA}${BOLD}Live Status: ${RESET}$live_status\n\";
printf \"${MAGENTA}${BOLD}Uploaded: ${RESET}$timestamp\n\";

ll=1
while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
echo


! [ \"$description\" = \"null\" ] && echo -n \"%s\";

" "$description" >"$CLI_PREVIEW_SCRIPTS_DIR/$(echo "$video" | jq ".title" -r | generate_sha256).txt"

  done
}

download_preview_images() {
  local url video filename

  echo generating preview in the background...
  generate_text_preview "$1" &

  ids="$(echo "$1" | jq '.entries[].id' -r 2>/dev/null)"
  urls="$(echo "$1" | jq '.entries[].thumbnails[-1].url' -r 2>/dev/null)"
  [ -z "$ids" ] && return 1
  [ -z "$urls" ] && return 1

  [ -f "$CLI_PREVIEW_IMAGES_CACHE_DIR/previews.txt" ] && rm "$CLI_PREVIEW_IMAGES_CACHE_DIR/previews.txt"
  lines="$(echo "$ids" | wc -l)"
  for i in $(seq 1 "$lines"); do
    video=$(echo "$1" | jq ".entries[$((i - 1))]")
    url=$(echo "$urls" | head -n $i | tail -n 1)
    filename=$(echo "$url" | generate_sha256)
    if ! [ -s "$CLI_PREVIEW_IMAGES_CACHE_DIR/${filename}.jpg" ]; then
      echo "url = \"${2}${url}\"" >>"$CLI_PREVIEW_IMAGES_CACHE_DIR/previews.txt"
      echo "output = \"$CLI_PREVIEW_IMAGES_CACHE_DIR/${filename}.jpg\"" >>"$CLI_PREVIEW_IMAGES_CACHE_DIR/previews.txt"
    fi
  done
  curl -s -K "$CLI_PREVIEW_IMAGES_CACHE_DIR/previews.txt" 2>/dev/null &
}

_preview_fzf_all() {
  PREVIEW_SCRIPT_FOR_VIDEOS="

  title={}
  id=\$(echo {} | generate_sha256)
  if  [ -f \"$CLI_PREVIEW_SCRIPTS_DIR/\${id}.txt\" ];then
    . \"$CLI_PREVIEW_SCRIPTS_DIR/\${id}.txt\";
  else
    echo Loading Preview...
  fi
"
  PREVIEW_SCRIPT_FOR_CHANNELS="

  MAGENTA='\x1b[38;2;215;0;95m'
  BOLD=\$(tput bold)
  RESET=\$(tput sgr0)

  if ! [ -z {} ] && ! [ {} = \"Back\" ] && ! [ {} = \"Exit\" ] && ! [ {} = \"Main Menu\" ];then
    channels_data=\$(cat \"\$CLI_CONFIG_DIR/subscriptions.json\")
    title=\"\$(echo {}|sed 's/\"/\\\\\\\"/g')\"
    video=\$(echo \"\$channels_data\" | jq -r \".entries | map(select(.title == \\\"\$title\\\" )) | .[0]\" 2>/dev/null)

    id=\$(echo \$video |jq '.thumbnails[-1].url' -r | generate_sha256);

    channel=\$(echo \"\$video\"| jq '.channel' -r);

    channel_follower_count=\$(echo \"\$video\"| jq -r '
    .channel_follower_count
    |tostring
    |split(\"\")
    |reverse
    |join(\"\")
    |gsub(\"(?<thousands>[0-9]\\{3})(?=[0-9])\"; \"\\(.thousands),\")
    |split(\"\")
    |reverse
    |join(\"\")
    '
    );
    
    description=\$(echo \"\$video\"| jq '.description' -r);
    
    if [ -f \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" ];then fzf_preview \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" 2>/dev/null;
    else echo loading preview image...;
    fi

    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
    # printf \"\${MAGENTA}\${BOLD}Id: \${RESET}\$id\n\";
    printf \"\${MAGENTA}\${BOLD}Channel: \${RESET}\$channel\n\";
    printf \"\${MAGENTA}\${BOLD}Follower Count: \${RESET}\$channel_follower_count followers\n\";

    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
    ! [ \"\$description\" = \"null\" ] && echo -e \"\$description\";
  else
    echo Loading...;
  fi;
"

  PREVIEW_SCRIPT_FOR_CHANNELS_EXPLORER="

  MAGENTA='\x1b[38;2;215;0;95m'
  BOLD=\$(tput bold)
  RESET=\$(tput sgr0)

  if ! [ -z {} ] && ! [ {} = \"Back\" ] && ! [ {} = \"Exit\" ] && ! [ {} = \"Main Menu\" ];then
    # channels_data=\$(cat \"\$CLI_CONFIG_DIR/subscriptions.json\")
    title=\"\$(echo {}|sed 's/\"/\\\\\\\"/g')\"
    video=\$(echo \"\$channels_data\" | jq -r \".entries | map(select(.title == \\\"\$title\\\" )) | .[0]\" 2>/dev/null)

    id=\$(echo \$video | jq '.thumbnails[-1].url' -r | generate_sha256);   

    channel=\$(echo \"\$video\"| jq '.channel' -r);

    channel_follower_count=\$(echo \"\$video\"| jq -r '
    .channel_follower_count
    |tostring
    |split(\"\")
    |reverse
    |join(\"\")
    |gsub(\"(?<thousands>[0-9]\\{3})(?=[0-9])\"; \"\\(.thousands),\")
    |split(\"\")
    |reverse
    |join(\"\")
    '
    );
    
    description=\$(echo \"\$video\"| jq '.description' -r);
    
    if [ -f \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" ];then fzf_preview \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" 2>/dev/null;
    else echo loading preview image...;
    fi

    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
    # printf \"\${MAGENTA}\${BOLD}Id: \${RESET}\$id\n\";
    printf \"\${MAGENTA}\${BOLD}Channel: \${RESET}\$channel\n\";
    printf \"\${MAGENTA}\${BOLD}Follower Count: \${RESET}\$channel_follower_count followers\n\";

    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
    ! [ \"\$description\" = \"null\" ] && echo -e \"\$description\";
  else
    echo Loading...;
  fi;
"
  PREVIEW_SCRIPT_FOR_PLAYLISTS_EXPLORER="

  MAGENTA='\x1b[38;2;215;0;95m'
  BOLD=\$(tput bold)
  RESET=\$(tput sgr0)

  if ! [ -z {} ] && ! [ {} = \"Back\" ] && ! [ {} = \"Exit\" ] && ! [ {} = \"Main Menu\" ];then
    # channels_data=\$(cat \"\$CLI_CONFIG_DIR/subscriptions.json\")
    title=\"\$(echo {}|sed 's/\"/\\\\\\\"/g')\"
    video=\$(echo \"\$playlist_results\" | jq -r \".entries | map(select(.title == \\\"\$title\\\" )) | .[0]\" 2>/dev/null)
    title=\"\$(echo \"\$title\"|sed 's/^.. //g')\"

    id=\$(echo \$video | jq '.thumbnails[-1].url' -r | generate_sha256);   

    
    if [ -f \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" ];then fzf_preview \"$CLI_PREVIEW_IMAGES_CACHE_DIR/\${id}.jpg\" 2>/dev/null;
    else echo loading preview image...;
    fi

    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
      echo \"\$title\";
    ll=1
    while [ \$ll -le \$FZF_PREVIEW_COLUMNS ];do echo -n -e \"─\" ;(( ll++ ));done;
  else
    echo Loading...;
  fi;
"

}

# ==============================================================================
# State Management
# ==============================================================================
get_channels_data() {
  [ "$FORCE_CHANNEL_THUMBNAILS_DOWNLOAD" = "0" ] && download_preview_images "$channels_data" "https:"
  if [ -f "$CLI_CONFIG_DIR/subscriptions.json" ] && ! [ "$force_update" = "1" ]; then
    channels_data=$(cat "$CLI_CONFIG_DIR/subscriptions.json")
  else
    echo Loading subscriptions...
    [ -n "$PREFERRED_BROWSER" ] && channels_data=$(yt-dlp "https://www.youtube.com/feed/channels" --flat-playlist $PREFERRED_BROWSER -J) || send_notification "Failed to fetch subscriptions (please set preferred browser in config)"
    ! [ "$FORCE_CHANNEL_THUMBNAILS_DOWNLOAD" = "0" ] && [ "$ENABLE_PREVIEW" = "true" ] && download_preview_images "$channels_data" "https:"
    [ -n "$channels_data" ] && ! [ "$channels_data" = "null" ] && echo "$channels_data" >"$CLI_CONFIG_DIR/subscriptions.json" || send_notification "Failed to fetch subscriptions"
    clear
  fi
}

run_yt_dlp() {
  if _dep_ch gum; then
    gum spin --show-output -- yt-dlp "$1" -J --flat-playlist --extractor-args youtubetab:approximate_date --playlist-start "$PLAYLIST_START" --playlist-end "$PLAYLIST_END" $PREFERRED_BROWSER || send_notification "Failed to fetch data : ("
  else
    echo "Loading..." >/dev/stderr
    yt-dlp "$1" -J --flat-playlist --extractor-args youtubetab:approximate_date --playlist-start "$PLAYLIST_START" --playlist-end "$PLAYLIST_END" $PREFERRED_BROWSER || send_notification "Failed to fetch data : ("
  fi
}

# ==============================================================================
# Menus: playlist actions
# ==============================================================================
__menu_playlist_actions_play_all() {
  if echo "$url" | grep -q "list=RD" || echo "$urlForAll" | grep -q "list=RD" || [ "$(echo "$search_results" | jq 'has("uploader_url") | not')" = "true" ]; then
    if [ -n "$urlForAll" ]; then
      # Fix YouTube Mix URLs FIRST

      # url="${url/&start_radio=0/}"
      # urlForAll="${urlForAll/&start_radio=1/}"
      cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "$urlForAll").m3u8"
      if ! [ -s "$cached_playlist" ]; then
        _mix_data=$(yt-dlp "$urlForAll" --flat-playlist -J)
        [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
        echo '#EXTM3U' >>"$cached_playlist"

        lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
        for i in $(seq 1 "$lines"); do
          local _video
          local _title
          local _channel
          local _url
          _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
          _title=$(echo "$_video" | jq ".title" -r)
          _channel=$(echo "$_video" | jq '.channel' -r)
          _url=$(echo "$_video" | jq '.url' -r)
          echo "#EXTINF:-1,$_title" >>"$cached_playlist"
          echo "$_url" >>"$cached_playlist"
          # echo "#EXTALB:Album Name" >>"$cached_playlist"
          # echo "#EXTGENRE:Genre" >>"$cached_playlist"
          # echo "#EXTGRP:Group Name" >>"$cached_playlist"
          echo "" >>"$cached_playlist"
        done
      fi
      "$MPV_CMD" "$cached_playlist"
    else
      cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "$url").m3u8"

      if ! [ -s "$cached_playlist" ]; then
        _mix_data=$(yt-dlp "$url" --flat-playlist -J)
        [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
        echo '#EXTM3U' >>"$cached_playlist"

        lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
        for i in $(seq 1 "$lines"); do
          local _video
          local _title
          local _channel
          local _url
          _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
          _title=$(echo "$_video" | jq ".title" -r)
          _channel=$(echo "$_video" | jq '.channel' -r)
          _url=$(echo "$_video" | jq '.url' -r)
          echo "#EXTINF:-1,$_title" >>"$cached_playlist"
          echo "$_url" >>"$cached_playlist"
          # echo "#EXTALB:Album Name" >>"$cached_playlist"
          # echo "#EXTGENRE:Genre" >>"$cached_playlist"
          # echo "#EXTGRP:Group Name" >>"$cached_playlist"
          echo "" >>"$cached_playlist"
        done
      fi
      "$MPV_CMD" "$cached_playlist"
    fi
  else
    if [ -n "$urlForAll" ]; then
      "$MPV_CMD" "$urlForAll"
    else
      "$MPV_CMD" "$url"
    fi
  fi

}

__menu_playlist_actions_listen_to_all() {
  if echo "$url" | grep -q "list=RD" || echo "$urlForAll" | grep -q "list=RD" || [ "$(echo "$search_results" | jq 'has("uploader_url") | not')" = "true" ]; then
    if [ -n "$urlForAll" ]; then
      cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "$urlForAll").m3u8"

      if ! [ -s "$cached_playlist" ]; then
        _mix_data=$(yt-dlp "$urlForAll" --flat-playlist -J)
        [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
        echo '#EXTM3U' >>"$cached_playlist"

        lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
        for i in $(seq 1 "$lines"); do
          local _video
          local _title
          local _channel
          local _url
          _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
          _title=$(echo "$_video" | jq ".title" -r)
          _channel=$(echo "$_video" | jq '.channel' -r)
          _url=$(echo "$_video" | jq '.url' -r)
          echo "#EXTINF:-1,$_title" >>"$cached_playlist"
          echo "$_url" >>"$cached_playlist"
          # echo "#EXTALB:Album Name" >>"$cached_playlist"
          # echo "#EXTGENRE:Genre" >>"$cached_playlist"
          # echo "#EXTGRP:Group Name" >>"$cached_playlist"
          echo "" >>"$cached_playlist"
        done
      fi
      "$MPV_CMD" "$cached_playlist" --no-video --force-window=no
    else
      cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "$url").m3u8"
      if ! [ -s "$cached_playlist" ]; then
        _mix_data=$(yt-dlp "$url" --flat-playlist -J)
        [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
        echo '#EXTM3U' >>"$cached_playlist"

        lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
        for i in $(seq 1 "$lines"); do
          local _video
          local _title
          local _channel
          local _url
          _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
          _title=$(echo "$_video" | jq ".title" -r)
          _channel=$(echo "$_video" | jq '.channel' -r)
          _url=$(echo "$_video" | jq '.url' -r)
          echo "#EXTINF:-1,$_title" >>"$cached_playlist"
          echo "$_url" >>"$cached_playlist"
          # echo "#EXTALB:Album Name" >>"$cached_playlist"
          # echo "#EXTGENRE:Genre" >>"$cached_playlist"
          # echo "#EXTGRP:Group Name" >>"$cached_playlist"
          echo "" >>"$cached_playlist"
        done
      fi
      "$MPV_CMD" "$cached_playlist" --no-video --force-window=no
    fi
  else
    if [ -n "$urlForAll" ]; then
      "$MPV_CMD" "$urlForAll" --no-video --force-window=no
    else
      "$MPV_CMD" "$url" --no-video --force-window=no
    fi
  fi
}

__menu_playlist_actions_toggle_enumerate_downloads() {
  if [ "$enumerate_playlist" = "" ]; then
    enumerate_playlist="%(playlist_index)s - "
  else
    enumerate_playlist=""
  fi
}

__menu_playlist_actions_download_all() {
  playlist_name=$(prompt "Name of the playlist" "$playlist_title")
  if [ -n "$urlForAll" ]; then
    # yt_dlp_cmd=("yt-dlp" "$urlForAll" "--output" "$DOWNLOAD_DIRECTORY/videos/$playlist_name/%(channel)s/$enumerate_playlist%(title)s.%(ext)s" $PREFERRED_BROWSER)
    # "${yt_dlp_cmd[@]}" --download-archive "$CLI_YT_DLP_ARCHIVE/$(echo -n -- "${yt_dlp_cmd[@]}" | generate_sha256)"
    :
  else
    # yt_dlp_cmd=("yt-dlp" "$url" "--output" "$DOWNLOAD_DIRECTORY/videos/$playlist_name/%(channel)s/$enumerate_playlist%(title)s.%(ext)s" $PREFERRED_BROWSER)
    # "${yt_dlp_cmd[@]}" --download-archive "$CLI_YT_DLP_ARCHIVE/$(echo -n -- "${yt_dlp_cmd[@]}" | generate_sha256)"
    :
  fi
  send_notification "Completed downloading of $playlist_name"

}

__menu_playlist_actions_download_all_audio() {
  playlist_name=$(prompt "Name of the playlist" "$playlist_title")

  if [ -n "$urlForAll" ]; then
    # yt_dlp_cmd=("yt-dlp" "$urlForAll" "--audio-format" "mp3" '-x' '-f' 'bestaudio/best' "--output" "$DOWNLOAD_DIRECTORY/audio/$playlist_name/%(channel)s/$enumerate_playlist%(title)s.%(ext)s" $PREFERRED_BROWSER)
    # "${yt_dlp_cmd[@]}" --download-archive "$CLI_YT_DLP_ARCHIVE/$(echo -n -- "${yt_dlp_cmd[@]}" | generate_sha256)"
    :
  else
    # yt_dlp_cmd=("yt-dlp" "$url" "--audio-format" "mp3" '-x' '-f' 'bestaudio/best' "--output" "$DOWNLOAD_DIRECTORY/audio/$playlist_name/%(channel)s/$enumerate_playlist%(title)s.%(ext)s" $PREFERRED_BROWSER)
    # "${yt_dlp_cmd[@]}" --download-archive "$CLI_YT_DLP_ARCHIVE/$(echo -n -- "${yt_dlp_cmd[@]}" | generate_sha256)"
    :
  fi
  send_notification "Completed downloading of $playlist_name"

}

__menu_playlist_actions_listen() {
  printf "${MAGENTA}Now Listening to:${RESET} %s\n" "$title"
  video_url=$(echo "$video" | jq '.url' -r)
  if echo "$video_url" | grep -q "list=RD"; then
    video_id=$(echo "$video" | jq '.id' -r | sed 's/RD//g')
    cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "https://www.youtube.com/watch?v=${video_id}&list=RD$video_id").m3u8"
    if ! [ -s "$cached_playlist" ]; then
      _mix_data=$(yt-dlp "https://www.youtube.com/watch?v=${video_id}&list=RD$video_id" --flat-playlist -J)
      [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
      echo '#EXTM3U' >>"$cached_playlist"

      lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
      for i in $(seq 1 "$lines"); do
        local _video
        local _title
        local _channel
        local _url
        _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
        _title=$(echo "$_video" | jq ".title" -r)
        _channel=$(echo "$_video" | jq '.channel' -r)
        _url=$(echo "$_video" | jq '.url' -r)
        echo "#EXTINF:-1,$_title" >>"$cached_playlist"
        echo "$_url" >>"$cached_playlist"
        # echo "#EXTALB:Album Name" >>"$cached_playlist"
        # echo "#EXTGENRE:Genre" >>"$cached_playlist"
        # echo "#EXTGRP:Group Name" >>"$cached_playlist"
        echo "" >>"$cached_playlist"
      done
    fi
    "$MPV_CMD" "$cached_playlist" --no-video --force-window=no
  else
    if ! [ "$PLAYER" = mpv ] && ! [ "$PLAYER" = tplay ] || [ "$PLATFORM" = android ]; then
      video_url=$(yt-dlp "$video_url" -q --no-warnings --get-url --format "bestaudio/best[height<=$VIDEO_QUALITY]/best" 2>/dev/null | tail -n 1)
      if ! [ "$?" = 0 ] || [ -z "$video_url" ]; then
        echo No video format found
        sleep 5
      fi
    fi
    case "$PLATFORM" in
    android)
      case "$PLAYER" in
      mpv | tplay) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
      vlc) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$title" >/dev/null 2>&1 & ;;
      esac
      ;;
    *)
      case "$PLAYER" in
      mpv)
        "$MPV_CMD" "$video_url" --no-video --force-window=no
        ;;
      vlc) vlc "$video_url" --video-title "$title" ;;
      tplay) tplay "$video_url" ;;
      esac
      ;;
    esac

  fi

  current_recent_videos='{"entries":[]}'
  [ -s "$CLI_CONFIG_DIR/recent.json" ] && current_recent_videos=$(cat "$CLI_CONFIG_DIR/recent.json")
  id=$(echo "$video" | jq '.id' -r)
  echo "$current_recent_videos" | jq "{\"entries\":[.entries[] | select(.id != \"$id\")]}|.entries+=[$(echo "$video" | jq '.title |= sub("^[0-9]+ "; "")')]" | jq "{\"entries\":.entries[-$NO_OF_RECENT:]}" >"$CLI_CONFIG_DIR/recent.json"

}

__menu_playlist_actions_mix() {

  local url0 _search_results
  video_id=$(echo "$video" | jq '.id' -r)
  url0=$urlForAll
  urlForAll="https://www.youtube.com/watch?v=${video_id}&list=RD$video_id"

  _search_results="$search_results"
  search_results=$(
    if _dep_ch gum; then
      gum spin --show-output -- yt-dlp "$urlForAll" -J --flat-playlist --extractor-args youtubetab:approximate_date $PREFERRED_BROWSER $PLAYLISTS_EXTRA_ARGS --playlist-start 1 --playlist-end $NO_OF_SEARCH_RESULTS
    else
      echo "Loading..." >/dev/stderr
      yt-dlp "$urlForAll" -J --flat-playlist --extractor-args youtubetab:approximate_date $PREFERRED_BROWSER $PLAYLISTS_EXTRA_ARGS --playlist-start 1 --playlist-end $NO_OF_SEARCH_RESULTS
    fi
  )
  playlist_explorer
  urlForAll=$url0
  search_results="$_search_results"
}

__menu_playlist_actions_watch() {
  printf "${MAGENTA}Now watching:${RESET} %s\n" "$title"

  video_url=$(echo "$video" | jq '.url' -r)
  if echo "$video_url" | grep -q "list=RD"; then
    local _mix_data
    video_id=$(echo "$video" | jq '.id' -r | sed 's/RD//g')

    cached_playlist="$CLI_AUTO_GEN_PLAYLISTS/$(generate_sha256 "https://www.youtube.com/watch?v=${video_id}&list=RD$video_id").m3u8"

    if ! [ -s "$cached_playlist" ]; then
      _mix_data=$(yt-dlp "https://www.youtube.com/watch?v=${video_id}&list=RD$video_id" --flat-playlist -J)
      [ -z "$_mix_data" ] && send_notification "Failed to get mix data"
      echo '#EXTM3U' >>"$cached_playlist"

      lines="$(echo "$_mix_data" | jq '.entries[].url' -r | wc -l)"
      for i in $(seq 1 "$lines"); do
        local _video
        local _title
        local _channel
        local _url
        _video=$(echo "$_mix_data" | jq ".entries[$((i - 1))]")
        _title=$(echo "$_video" | jq ".title" -r)
        _channel=$(echo "$_video" | jq '.channel' -r)
        _url=$(echo "$_video" | jq '.url' -r)
        echo "#EXTINF:-1,$_title" >>"$cached_playlist"
        echo "$_url" >>"$cached_playlist"
        # echo "#EXTALB:Album Name" >>"$cached_playlist"
        # echo "#EXTGENRE:Genre" >>"$cached_playlist"
        # echo "#EXTGRP:Group Name" >>"$cached_playlist"
        echo "" >>"$cached_playlist"
      done
    fi
    "$MPV_CMD" "$cached_playlist"
  else
    if ! [ "$PLAYER" = mpv ] && ! [ "$PLAYER" = tplay ] || [ "$PLATFORM" = android ]; then
      video_url=$(yt-dlp "$video_url" -q --no-warnings --get-url --format "best[height<=$VIDEO_QUALITY]/best" 2>/dev/null | tail -n 1)
      if ! [ "$?" = 0 ] || [ -z "$video_url" ]; then
        echo No video format found
        sleep 5
      fi
    fi
    case "$PLATFORM" in
    android)
      case "$PLAYER" in
      mpv | tplay) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
      vlc) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$title" >/dev/null 2>&1 & ;;
      esac
      ;;
    *)
      case "$PLAYER" in
      mpv)
        "$MPV_CMD" "$video_url"
        ;;
      vlc) vlc "$video_url" --video-title "$title" ;;
      tplay) tplay "$video_url" ;;
      esac
      ;;
    esac

  fi

  current_recent_videos='{"entries":[]}'
  [ -s "$CLI_CONFIG_DIR/recent.json" ] && current_recent_videos=$(cat "$CLI_CONFIG_DIR/recent.json")
  id=$(echo "$video" | jq '.id' -r)
  echo "$current_recent_videos" | jq "{\"entries\":[.entries[] | select(.id != \"$id\")]}|.entries+=[$(echo "$video" | jq '.title |= sub("^[0-9]+ "; "")')]" | jq "{\"entries\":.entries[-$NO_OF_RECENT:]}" >"$CLI_CONFIG_DIR/recent.json"
}

__menu_playlist_actions_save() {
  # For now a pseudo like feature is just as useful
  current_liked_videos='{"entries":[]}'
  [ -s "$CLI_CONFIG_DIR/saved_videos.json" ] && current_liked_videos=$(cat "$CLI_CONFIG_DIR/saved_videos.json")
  id=$(echo "$video" | jq '.id' -r)
  echo "$current_liked_videos" | jq "{\"entries\":[.entries[] | select(.id != \"$id\")]}|.entries+=[$(echo "$video" | jq '.title |= sub("^[0-9]+ "; "")')]" >"$CLI_CONFIG_DIR/saved_videos.json"

}

__menu_playlist_actions_save_playlist() {
  # For now a pseudo like feature is just as useful
  custom_playlists="[]"
  [ -s "$CLI_CONFIG_DIR/custom_playlists.json" ] && custom_playlists=$(cat "$CLI_CONFIG_DIR/custom_playlists.json")
  playlist_name=$(prompt "Enter the name of the playlist" "$playlist_title")
  if [ -n "$urlForAll" ]; then
    playlist_id=$(echo "$urlForAll" | sed 's/.*list=//g')
  else
    playlist_id=$(echo "$url" | sed 's/.*list=//g')
  fi
  custom_playlist="
          {
            \"name\": \"$playlist_name\",
            \"playlistUrl\": \"https://www.youtube.com/playlist?list=$playlist_id\",
            \"playlistWatchUrl\": \"https://www.youtube.com/watch?list=$playlist_id\"
          }
        "
  echo "$custom_playlists" | jq ".+=[$custom_playlist]" >"$CLI_CONFIG_DIR/custom_playlists.json" && send_notification "successfully added to custom playlists" || send_notification "Failed to add to custom playlists"

}

__menu_playlist_actions_unsave() {
  current_liked_videos='{"entries":[]}'
  [ -s "$CLI_CONFIG_DIR/saved_videos.json" ] && current_liked_videos=$(cat "$CLI_CONFIG_DIR/saved_videos.json")
  id=$(echo "$video" | jq '.id' -r)
  echo "$current_liked_videos" | jq "{\"entries\":[.entries[] | select(.id != \"$id\")]}" >"$CLI_CONFIG_DIR/saved_videos.json"
}

__menu_playlist_actions_subscribe_to_channel() {
  # TODO: use youtube api to enable video subscriptions
  send_notification "contribute to the project by adding this feature"
  sleep "$NOTIFICATION_DURATION"
}

__menu_playlist_actions_visit_channel() {
  # TODO: use youtube api to enable video subscriptions
  send_notification "contribute to the project by adding this feature"
  sleep "$NOTIFICATION_DURATION"
}

__menu_playlist_actions_open_in_browser() {
  if _dep_ch open; then
    open "$(echo "$video" | jq '.url' -r)"
  elif _dep_ch xdg-open; then
    xdg-open "$(echo "$video" | jq '.url' -r)"
  else
    send_notification "Could not find xdg-open or open"
  fi

}

__menu_playlist_actions_download() {
  video_url=$(echo "$video" | jq '.url' -r)
  yt-dlp "$video_url" --output "$DOWNLOAD_DIRECTORY/videos/individual/%(channel)s/%(title)s.%(ext)s" $PREFERRED_BROWSER
  send_notification "Completed downloading of $title"

}

__menu_playlist_actions_download_audio() {
  video_url=$(echo "$video" | jq '.url' -r)
  yt-dlp "$video_url" -x -f 'bestaudio' --audio-format mp3 --output "$DOWNLOAD_DIRECTORY/audio/individual/%(channel)s/%(title)s.%(ext)s" $PREFERRED_BROWSER
  send_notification "Completed downloading of $title"

}

__menu_playlist_actions_shell() {
  video_url=$(echo "$video" | jq '.url' -r)
  export url urlForAll search_results video video_url playlist_title CLI_HEADER CLI_NAME DOWNLOAD_DIRECTORY CLI_YT_DLP_ARCHIVE
  local init_text="\
$CLI_HEADER
Welcome to the $CLI_NAME shell.
You can use the following:
 variables:
    - url
    - urlForAll
    - search_results
    - video
    - video_url
    - playlist_title
    - DOWNLOAD_DIRECTORY
    - CLI_YT_DLP_ARCHIVE
  functions:
    - generate_sha256
"
  user_shell="$(ps -o comm= -p "$PPID")"
  if [ "$user_shell" = "fish" ]; then
    fish --init-command "function fish_greeting; clear;echo \"$init_text\"; end"
  else
    # bash --rcfile <(echo "[ -f ~/.bashrc ] && . ~/.bashrc;clear;echo \"$init_text\"")
    :
  fi

}

_menu_playlist_actions() {
  local actions
  local media_action
  actions="\
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_WATCH}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_PLAY_ALL}
${THEME_FZF_ICON_COLOR_PRIMARY}󰎆${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_LISTEN}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_LISTEN_ALL}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_MIX}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_SAVE}
${THEME_FZF_ICON_COLOR_PRIMARY}󰧎${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_UNSAVE}
${THEME_FZF_ICON_COLOR_PRIMARY}󰐒${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_SAVE_PLAYLIST}
${THEME_FZF_ICON_COLOR_PRIMARY}󰵀${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_SUBSCRIBE}
${THEME_FZF_ICON_COLOR_PRIMARY}󱑤${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD}
${THEME_FZF_ICON_COLOR_PRIMARY}󰦗${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL}
${THEME_FZF_ICON_COLOR_PRIMARY}󱑤${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_AUDIO}
${THEME_FZF_ICON_COLOR_PRIMARY}󰦗${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL_AUDIO}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_BROWSER}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_TOGGLE_ENUM}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_SHELL}
${THEME_FZF_ICON_COLOR_PRIMARY}󰌍${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_BACK}
${THEME_FZF_ICON_COLOR_ERROR}󰈆${THEME_RESET}  ${TXT_MENU_PLAYLIST_ACTIONS_EXIT}"

  while true; do
    media_action="$(printf "%s" "$actions" | launcher "$TXT_MENU_PLAYLIST_ACTIONS_PROMPT" | sed 's/.  //g')"
    clear
    case "$media_action" in
    "$TXT_MENU_PLAYLIST_ACTIONS_WATCH") __menu_playlist_actions_watch ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_PLAY_ALL") __menu_playlist_actions_handle_play_all ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_LISTEN") __menu_playlist_actions_listen ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_LISTEN_ALL") __menu_playlist_actions_listen_to_all ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_MIX") __menu_playlist_actions_mix ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_SAVE") __menu_playlist_actions_save ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_UNSAVE") __menu_playlist_actions_unsave ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_SAVE_PLAYLIST") __menu_playlist_actions_save_playlist ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_SUBSCRIBE") __menu_playlist_actions_subscribe_to_channel ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD") __menu_playlist_actions_download ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL") __menu_playlist_actions_download_all ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_AUDIO") __menu_playlist_actions_download_audio ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_DOWNLOAD_ALL_AUDIO") __menu_playlist_actions_download_all_audio ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_BROWSER") __menu_playlist_actions_open_in_browser ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_TOGGLE_ENUM") __menu_playlist_actions_toggle_enumerate_downloads ;;
    "$TXT_MENU_PLAYLIST_ACTIONS_SHELL") __menu_playlist_actions_shell ;;
    "$TXT_MENU_BACK" | "") break ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    *) _ui_notify "${TXT_MENU_INVALID_ACTION}: $media_action" ;;
    esac
    clear
  done
}

menu_playlist_actions() {
  _menu_playlist_actions
}

# ==============================================================================
# Menus: playlist explorer
# ==============================================================================
__menu_playlist_explorer_next() {
  PLAYLIST_START=$((PLAYLIST_START + "$NO_OF_SEARCH_RESULTS"))
  PLAYLIST_END=$((PLAYLIST_END + "$NO_OF_SEARCH_RESULTS"))
  search_results=$(run_yt_dlp "$url")
  DOWNLOAD_IMAGES=0

}

__menu_playlist_explorer_previous() {
  PLAYLIST_START=$((PLAYLIST_START - "$NO_OF_SEARCH_RESULTS"))
  [ $PLAYLIST_START -le 0 ] && PLAYLIST_START=1
  PLAYLIST_END=$((PLAYLIST_END - "$NO_OF_SEARCH_RESULTS"))
  [ $PLAYLIST_END -le "$NO_OF_SEARCH_RESULTS" ] && PLAYLIST_END="$NO_OF_SEARCH_RESULTS"
  search_results=$(run_yt_dlp "$url")
  DOWNLOAD_IMAGES=0

}

_menu_playlist_explorer() {
  local search_results
  local titles
  local choices
  choices="\
    $TXT_MENU_NEXT
    $TXT_MENU_PREVIOUS
    $TXT_MENU_BACK
    $TXT_MENU_EXIT
    "
  while true; do
    search_results=$(echo "$search_results" | jq "
          .entries=(.entries 
          | to_entries
          | map(.value.title=\"\(.key+1|tostring| if (.|length) < 2 then \"0\" + . else . end) \"+.value.title) 
          |map(.value))
          ")
    titles=$(echo "$search_results" | jq '.entries[].title' -r 2>/dev/null)
    title="$(printf "%s\n%s" "$titles" "$choices" | launcher_with_preview "$TXT_MENU_PLAYLIST_EXPLORER_PROMPT" "playlist" | tr -d '\n' | sed 's/^[^0-9]  //g' | sed 's/"/\\"/g')"
    clear

    case "$title" in
    "$TXT_MENU_NEXT") __menu_playlist_explorer_next ;;
    "$TXT_MENU_PREVIOUS") __menu_playlist_explorer_previous ;;
    "$TXT_MENU_BACK" | "") break ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    esac
    _menu_playlist_actions
  done
}

menu_playlist_explorer() {
  _menu_playlist_explorer
}

# ==============================================================================
# Menus: channels actions
# ==============================================================================
__menu_channel_actions_subscribe() {
  if ! [ -s "$CLI_CONFIG_DIR/subscriptions.json" ]; then
    if confirm "Would you like to import your youtube subscriptions first? You wont be able to do so again unless you delete subscriptions.json"; then
      _channels_data=$(yt-dlp "https://www.youtube.com/feed/channels" --flat-playlist $PREFERRED_BROWSER -J)
      echo "$_channels_data" >"$CLI_CONFIG_DIR/subscriptions.json"
    else

      _channels_data='{"entries":[]}'
    fi
  else
    _channels_data=$(cat "$CLI_CONFIG_DIR/subscriptions.json")
  fi

  id=$(echo "$channel" | jq '.id' -r)
  echo "$_channels_data" | jq "{\"entries\":[.entries[] | select(.id != \"$id\")]}|.entries+=[$channel]" >"$CLI_CONFIG_DIR/subscriptions.json" && send_notification "successfully subscribed" || send_notification "Failed to subscribe to channel"

}

_menu_channel_actions() {
  local actions
  actions="\
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_VIDEOS}
${THEME_FZF_ICON_COLOR_PRIMARY}󰩉${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_FEATURED}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_SEARCH}
${THEME_FZF_ICON_COLOR_PRIMARY}󰐑${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_PLAYLISTS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_SHORTS}
${THEME_FZF_ICON_COLOR_PRIMARY}󰠿${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_STREAMS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_PODCASTS}
${THEME_FZF_ICON_COLOR_PRIMARY}󰵀${THEME_RESET}  ${TXT_MENU_CHANNEL_ACTIONS_SUBSCRIBE}
${THEME_FZF_ICON_COLOR_PRIMARY}󰌍${THEME_RESET}  ${TXT_MENU_BACK}
${THEME_FZF_ICON_COLOR_ERROR}󰈆${THEME_RESET}  ${TXT_MENU_EXIT}"

  while true; do
    action="$(printf "%s" "$actions" | launcher "$TXT_MENU_CHANNEL_ACTIONS_PROMPT" | sed 's/.  //g')"
    uploader_url_base="$(echo "$channel" | jq '.uploader_url' -r)"
    clear

    case "$action" in
    "$TXT_MENU_CHANNEL_ACTIONS_VIDEOS")
      url="$uploader_url_base/videos"
      search_results=$(run_yt_dlp "$url")
      playlist_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_STREAMS")
      url="$uploader_url_base/streams"
      search_results=$(run_yt_dlp "$url")
      playlist_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_PODCASTS")
      url="$uploader_url_base/podcasts"
      playlists_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_SHORTS")
      url="$uploader_url_base/shorts"
      search_results=$(run_yt_dlp "$url")
      playlist_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_FEATURED")
      url="$uploader_url_base/featured"
      playlists_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_PLAYLISTS")
      url="$uploader_url_base/playlists"
      playlists_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_SEARCH")
      search_term="$(_ui_prompt "Enter term to search for" | jq -Rr '@uri')"
      url="$uploader_url_base/search?query=$search_term"
      search_results=$(run_yt_dlp "$url")
      playlist_explorer
      ;;
    "$TXT_MENU_CHANNEL_ACTIONS_SUBSCRIBE") __menu_channel_actions_subscribe ;;
    "$TXT_MENU_BACK" | "") break ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    *) _ui_notify "$TXT_MENU_INVALID_ACTION" ;;
    esac
    clear
  done

}

menu_channel_actions() {
  _menu_channel_actions
}

# ==============================================================================
# Menus: channels explorer
# ==============================================================================
_menu_channels_explorer() {
  while true; do
    channels=$(echo "$channels_data" | jq '.entries[].channel' -r)
    export SHELL CLI_CONFIG_DIR
    channel_name=$(printf "%s\nMain Menu\nExit" "$channels" | launcher_with_preview "Select Channel" "$PREVIEW_SCRIPT_FOR_CHANNELS")
    channel_name="$(echo "$channel_name" | sed 's/"/\\"/g;s/ *$//g' | tr -d "\n")"
    [ "$channel_name" = "Exit" ] && byebye
    [ "$channel_name" = "Main Menu" ] && break
    channel="$(echo "$channels_data" | jq ".entries|map(select(.channel == \"$channel_name\"))|.[0]")"
    channels_explorer
  done
}

menu_channels_explorer() {
  _menu_channels_explorer
}

# ==============================================================================
# Menus: miscellaneous
# ==============================================================================
__menu_miscellaneous_explore_channels() {
  local search_term
  while true; do
    clear
    search_term=$(prompt "What channel would you like to explore?")
    url="https://www.youtube.com/results?search_query=$search_term&sp=EgIQAg%253D%253D"
    echo "Loading..." >/dev/stderr
    channels_data=$(yt-dlp "$url" -J --flat-playlist --extractor-args youtubetab:approximate_date $PREFERRED_BROWSER --playlist-start 1 --playlist-end $NO_OF_SEARCH_RESULTS)
    clear
    channels=$(echo "$channels_data" | jq '.entries[].channel' -r)
    export channels_data SHELL
    channel_name=$(printf "%s\nBack\nExit" "$channels" | launcher_with_preview "Select Channel" "$PREVIEW_SCRIPT_FOR_CHANNELS_EXPLORER")
    channel_name="$(echo "$channel_name" | sed 's/"/\\"/g;s/ *$//g' | tr -d "\n")"
    [ "$channel_name" = "Exit" ] && byebye
    [ "$channel_name" = "Back" ] || [ "$channel_name" = "" ] && break
    channel="$(echo "$channels_data" | jq ".entries|map(select(.channel == \"$channel_name\"))|.[0]")"
    channels_explorer
  done

}

__menu_miscellaneous_explore_playlists() {
  search_term=$(prompt "What playlist would you like to explore?")
  url="https://www.youtube.com/results?search_query=$search_term&sp=EgIQAw%253D%253D"
  PLAYLISTS_EXTRA_ARGS="--playlist-start 1 --playlist-end $NO_OF_SEARCH_RESULTS"
  playlists_explorer

}

__menu_miscellaneous_search_history() {
  while true; do
    ! [ -s "$CLI_CACHE_DIR/search_history.txt" ] && echo "No search history or disabed" && sleep "$NOTIFICATION_DURATION" && main
    search_term="$(printf "$(tac "$CLI_CACHE_DIR/search_history.txt")\nBack" | launcher "Search for" | jq -Rr '@uri')"
    [ "$search_term" = "Back" ] || [ "$search_term" = "" ] && break
    url="https://www.youtube.com/results?search_query=$search_term&sp=EgIQAQ%253D%253D"
    search_results=$(run_yt_dlp "$url")
    playlist_explorer
  done

}

__menu_miscellaneous_new_custom_command() {
  custom_yt_dlp_cmd=$(prompt "Enter the custom yt-dlp command" "yt-dlp -J --flat-playlist --extractor-args youtubetab:approximate_date $PREFERRED_BROWSER https://youtube.com")
  custom_cmds="[]"
  [ -s "$F_CUSTOM_CMDS" ] && custom_cmds=$(cat "$F_CUSTOM_CMDS")
  custom_cmd_name=$(prompt "Enter the name of the new custom command")
  custom_cmd="
          {
            \"name\": \"$custom_cmd_name\",
            \"cmd\": \"$custom_yt_dlp_cmd\"
          }
        "
  echo "$custom_cmds" | jq ".+=[$custom_cmd]" >"$F_CUSTOM_CMDS" && send_notification "successfully added to custom cmds" || send_notification "Failed to add to custom cmds"

  echo Running new custom command...
  search_results=$(
    if command -v "gum" >/dev/null 2>&1; then
      gum spin --show-output --show-error -- $custom_yt_dlp_cmd || send_notification "Failed to fetch data : ("
    else
      echo "Loading..." >/dev/stderr
      $custom_yt_dlp_cmd || send_notification "Failed to fetch data : ("
    fi
  )

  playlist_explorer

}

__menu_miscellaneous_custom_commands() {
  ! [ -s "$F_CUSTOM_CMDS" ] && send_notification "You dont have any custom cmds. Create them here: <$F_CUSTOM_CMDS>"
  while true; do
    custom_cmd_name=$(printf "%s\nBack" "$(jq -r '.[].name' "$F_CUSTOM_CMDS")" | launcher "Select Custom Data Loader Command To Run")
    [ "$custom_cmd_name" = "Back" ] || [ "$custom_cmd_name" = "" ] && break
    custom_yt_dlp_cmd=$(jq -r ". | map(select(.name == \"$custom_cmd_name\" )) | .[0].cmd" "$F_CUSTOM_CMDS")
    echo Running custom command...
    search_results=$(
      if _dep_ch gum; then
        gum spin --show-output --show-error -- $custom_yt_dlp_cmd || send_notification "Failed to fetch data : ("
      else
        echo "Loading..." >/dev/stderr
        $custom_yt_dlp_cmd || send_notification "Failed to fetch data : ("
      fi
    )
    playlist_explorer
  done

}

__menu_miscellaneous_edit_search_history() {
  if _dep_ch "$PREFERRED_EDITOR"; then
    $PREFERRED_EDITOR "$CLI_CACHE_DIR/search_history.txt"
  elif _dep_ch "$EDITOR"; then
    $EDITOR "$CLI_CACHE_DIR/search_history.txt"
  elif _dep_ch "open"; then
    open "$CLI_CACHE_DIR/search_history.txt"
  elif _dep_ch "xdg-open"; then
    xdg-open "$CLI_CACHE_DIR/search_history.txt"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi

}

__menu_miscellaneous_edit_custom_playlists() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "$CLI_CACHE_DIR/custom_playlists.txt"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "$CLI_CONFIG_DIR/custom_playlists.json"
  elif command -v "open" >/dev/null 2>&1; then
    open "$CLI_CONFIG_DIR/custom_playlists.json"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "$CLI_CONFIG_DIR/custom_playlists.json"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi

}

__menu_miscellaneous_edit_custom_commands() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "$F_CUSTOM_CMDS"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "$F_CUSTOM_CMDS"
  elif command -v "open" >/dev/null 2>&1; then
    open "$F_CUSTOM_CMDS"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "$F_CUSTOM_CMDS"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi

}

__menu_miscellaneous_edit_mpv_config() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "${XDG_CONFIG_HOME:-"$HOME"/.config}/mpv/mpv.conf"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "${XDG_CONFIG_HOME:-"$HOME"/.config}/mpv/mpv.conf"
  elif command -v "open" >/dev/null 2>&1; then
    open "${XDG_CONFIG_HOME:-"$HOME"/.config}/mpv/mpv.conf"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "${XDG_CONFIG_HOME:-"$HOME"/.config}/mpv/mpv.conf"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi
}

__menu_miscellaneous_edit_yt_dlp_config() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "${XDG_CONFIG_HOME:-"$HOME"/.config}/yt-dlp/config"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "${XDG_CONFIG_HOME:-"$HOME"/.config}/yt-dlp/config"
  elif command -v "open" >/dev/null 2>&1; then
    open "${XDG_CONFIG_HOME:-"$HOME"/.config}/yt-dlp/config"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "${XDG_CONFIG_HOME:-"$HOME"/.config}/yt-dlp/config"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi

}

__menu_miscellaneous_clear_search_history() {
  confirm "Are you sure you want to clear your search history ($CLI_CACHE_DIR/search_history.txt)?" && rm "$CLI_CACHE_DIR/search_history.txt"

}

__menu_miscellaneous_sync_youtube_subscriptions() {
  if confirm "This will erase your local subs, proceed?"; then
    echo "Syncing subscriptions..."
    [ -n "$PREFERRED_BROWSER" ] && channels_data=$(yt-dlp "https://www.youtube.com/feed/channels" --flat-playlist $PREFERRED_BROWSER -J) || send_notification "Failed to fetch subscriptions (please set preferred browser in config"
    download_preview_images "$channels_data" "https:"
    [ -n "$channels_data" ] && ! [ "$channels_data" = "null" ] && echo "$channels_data" >"$CLI_CONFIG_DIR/subscriptions.json" && send_notification "successfully imported yt subs" || send_notification "Failed to fetch subscriptions"
  else
    send_notification "Sync cancelled"
  fi

}

_menu_miscellaneous() {
  local actions
  actions="\
${THEME_FZF_ICON_COLOR_PRIMARY}󰵀${THEME_RESET}  ${TXT_MENU_MISC_EXPLORE_CHANNELS}
${THEME_FZF_ICON_COLOR_PRIMARY}󰐑${THEME_RESET}  ${TXT_MENU_MISC_EXPLORE_PLAYLISTS}
${THEME_FZF_ICON_COLOR_PRIMARY}󱘢${THEME_RESET}  ${TXT_MENU_MISC_SEARCH_HISTORY}
${THEME_FZF_ICON_COLOR_PRIMARY}󰆺${THEME_RESET}  ${TXT_MENU_MISC_NEW_CUSTOM_CMD}
${THEME_FZF_ICON_COLOR_PRIMARY}󰡦${THEME_RESET}  ${TXT_MENU_MISC_CUSTOM_CMDS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MISC_EDIT_SEARCH_HISTORY}
${THEME_FZF_ICON_COLOR_PRIMARY}󰤀${THEME_RESET}  ${TXT_MENU_MISC_EDIT_CUSTOM_PLAYLISTS}
${THEME_FZF_ICON_COLOR_PRIMARY}󱄢${THEME_RESET}  ${TXT_MENU_MISC_EDIT_MPV_CONFIG}
${THEME_FZF_ICON_COLOR_PRIMARY}󰮆${THEME_RESET}  ${TXT_MENU_MISC_EDIT_YTDLP_CONFIG}
${THEME_FZF_ICON_COLOR_PRIMARY}󱘫${THEME_RESET}  ${TXT_MENU_MISC_EDIT_CUSTOM_CMDS}
${THEME_FZF_ICON_COLOR_PRIMARY}󰓦${THEME_RESET}  ${TXT_MENU_MISC_SYNC_SUBS}
${THEME_FZF_ICON_COLOR_ERROR}󰆴${THEME_RESET}  ${TXT_MENU_MISC_CLEAR_SEARCH_HISTORY}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_BACK}
${THEME_FZF_ICON_COLOR_ERROR}󰈆${THEME_RESET}  ${TXT_MENU_EXIT}"
  while true; do
    action="$(printf "%s" "$actions" | launcher "$TXT_MENU_MISC_PROMPT" | sed 's/.*  //g')"
    clear

    case "$action" in
    "$TXT_MENU_MISC_EXPLORE_CHANNELS") __menu_miscellaneous_explore_channels ;;
    "$TXT_MENU_MISC_EXPLORE_PLAYLISTS") __menu_miscellaneous_explore_playlists ;;
    "$TXT_MENU_MISC_SEARCH_HISTORY") __menu_miscellaneous_search_history ;;
    "$TXT_MENU_MISC_NEW_CUSTOM_CMD") __menu_miscellaneous_new_custom_command ;;
    "$TXT_MENU_MISC_CUSTOM_CMDS") __menu_miscellaneous_custom_commands ;;
    "$TXT_MENU_MISC_EDIT_SEARCH_HISTORY") __menu_miscellaneous_edit_search_history ;;
    "$TXT_MENU_MISC_EDIT_CUSTOM_PLAYLISTS") __menu_miscellaneous_edit_custom_playlists ;;
    "$TXT_MENU_MISC_EDIT_MPV_CONFIG") __menu_miscellaneous_edit_mpv_config ;;
    "$TXT_MENU_MISC_EDIT_YTDLP_CONFIG") __menu_miscellaneous_edit_yt_dlp_config ;;
    "$TXT_MENU_MISC_EDIT_CUSTOM_CMDS") __menu_miscellaneous_edit_custom_commands ;;
    "$TXT_MENU_MISC_SYNC_SUBS") __menu_miscellaneous_sync_youtube_subscriptions ;;
    "$TXT_MENU_MISC_CLEAR_SEARCH_HISTORY") __menu_miscellaneous_clear_search_history ;;
    "$TXT_MENU_BACK" | "") break ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    *) _ui_notify_error "$TXT_MENU_INVALID_ACTION" ;;
    esac
    clear
  done

}

menu_miscellaneous() {
  _menu_miscellaneous
}

# ==============================================================================
# Menus: main
# ==============================================================================
__menu_main_feed() {
  url="https://www.youtube.com/feed/subscriptions"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_trending() {
  url="https://www.youtube.com/feed/trending"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_playlists() {
  url="https://www.youtube.com/feed/library"
  # Note: Use playlists_explorer if you want to list the containers
  playlists_explorer
}

__menu_main_search() {
  clear
  local search_term
  search_term="$(prompt "Enter search term" | jq -Rr '@uri')"
  url="https://www.youtube.com/results?search_query=$search_term"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_watch_later() {
  url="https://www.youtube.com/playlist?list=WL"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_subscription_feed() {
  url="https://www.youtube.com/feed/subscriptions"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_custom_playlists() {
  ! [ -s "$CUSTOM_PLAYLISTS" ] && echo "You don't have any custom playlists. Create them here: <$CUSTOM_PLAYLISTS>" && sleep "$NOTIFICATION_DURATION" && main
  while true; do
    playlist_title=$(printf "%s\nBack" "$(jq -r '.|reverse|.[].name' "$CUSTOM_PLAYLISTS")" | launcher "Select Custom Playlist To Play")
    [ "$playlist_title" = "Back" ] || [ "$playlist_title" = "" ] && break
    url=$(jq -r ". | map(select(.name == \"$playlist_title\" )) | .[0].playlistWatchUrl" "$CUSTOM_PLAYLISTS")
    urlForAll=$(jq -r ". | map(select(.name == \"$playlist_title\" )) | .[0].playlistUrl" "$CUSTOM_PLAYLISTS")
    search_results=$(run_yt_dlp "$url")
    playlist_explorer
  done
}

__menu_main_liked_videos() {
  url="https://www.youtube.com/playlist?list=LL"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_saved_videos() {
  ! [ -s "$CLI_CONFIG_DIR/saved_videos.json" ] && echo No saved videos && sleep "$NOTIFICATION_DURATION" && main
  search_results=$(jq '{"entries":.entries|reverse}' "$CLI_CONFIG_DIR/saved_videos.json")
  playlist_explorer
}

__menu_main_watch_history() {
  url="https://www.youtube.com/feed/history"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_recent() {
  # Often treated as a subset of history
  url="https://www.youtube.com/feed/history"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_clips() {
  url="https://www.youtube.com/feed/clips"
  search_results=$(run_yt_dlp "$url")
  playlist_explorer
}

__menu_main_edit_config() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "open" >/dev/null 2>&1; then
    open "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open"
  fi
  load_config
}

_menu_main() {
  local actions
  actions="\
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_FEED}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_TRENDING}
${THEME_FZF_ICON_COLOR_PRIMARY}󰐑${THEME_RESET}  ${TXT_MENU_MAIN_PLAYLISTS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_SEARCH}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_WATCH_LATER}
${THEME_FZF_ICON_COLOR_PRIMARY}󰵀${THEME_RESET}  ${TXT_MENU_MAIN_SUBS_FEED}
${THEME_FZF_ICON_COLOR_PRIMARY}󰑈${THEME_RESET}  ${TXT_MENU_MAIN_CHANNELS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_CUSTOM_PLAYLISTS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_LIKED}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_SAVED}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_HISTORY}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_RECENT}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_CLIPS}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_EDIT_CONFIG}
${THEME_FZF_ICON_COLOR_PRIMARY}${THEME_RESET}  ${TXT_MENU_MAIN_MISC}
${THEME_FZF_ICON_COLOR_ERROR}󰈆${THEME_RESET}  ${TXT_MENU_EXIT}"

  action="$(printf "%s" "$actions" | launcher "Select Action" | sed 's/.*  //g')"
  case "$action" in
  "$TXT_MENU_MAIN_FEED") __menu_main_feed ;;
  "$TXT_MENU_MAIN_TRENDING") __menu_main_trending ;;
  "$TXT_MENU_MAIN_PLAYLISTS") __menu_main_playlists ;;
  "$TXT_MENU_MAIN_SEARCH") __menu_main_search ;;
  "$TXT_MENU_MAIN_WATCH_LATER") __menu_main_watch_later ;;
  "$TXT_MENU_MAIN_SUBS_FEED") __menu_main_subscription_feed ;;
  "$TXT_MENU_MAIN_CHANNELS") _menu_channels_explorer ;;
  "$TXT_MENU_MAIN_CUSTOM_PLAYLISTS") __menu_main_custom_playlists ;;
  "$TXT_MENU_MAIN_LIKED") __menu_main_liked_videos ;;
  "$TXT_MENU_MAIN_SAVED") __menu_main_saved_videos ;;
  "$TXT_MENU_MAIN_HISTORY") __menu_main_watch_history ;;
  "$TXT_MENU_MAIN_RECENT") __menu_main_recent ;;
  "$TXT_MENU_MAIN_CLIPS") __menu_main_clips ;;
  "$TXT_MENU_MAIN_EDIT_CONFIG") __menu_main_edit_config ;;
  "$TXT_MENU_MAIN_MISC") _menu_miscellaneous ;;
  "$TXT_MENU_EXIT" | "") _util_byebye ;;
  *) _ui_notify_error "$TXT_MENU_INVALID_ACTION" ;;
  esac
}

menu_main() {
  _menu_main
}

# ==============================================================================
# APP: utils
# ==============================================================================
_app_util_update_script() {
  local update
  if [ -z "$CLI_PATH" ]; then
    ui_notify_critical "Can't find $CLI_NAME in PATH"
  fi

  if [ ! -w "$CLI_PATH" ]; then
    ui_confirm "It seems you have installed $CLI_NAME as root, which is not recommended. Do you still want to update using sudo? (I recommended reinstalling the cli as non root)" || _util_byebye
    if _dep_ch sudo; then
      exec sudo -s "$CLI_PATH" "-u"
    else
      ui_notify_critical "Insufficient permissions to update and can't find sudo in PATH"
    fi
  fi

  update=$(curl -s "$CLI_URL")
  [ -z "$update" ] && ui_notify_critical "Failed to fetch update information"
  update="$(printf "%s\n" "$update" | diff -u "$CLI_PATH" - 2>/dev/null)"
  if [ -z "$update" ]; then
    ui_notify "Script is up to date :)"
  else
    if printf "%s" "$update" | patch "$CLI_PATH" -; then
      ui_notify "Script has been updated!"
    else
      ui_notify_critical "Can't update for some reason!"
    fi
  fi
  exec "$CLI_PATH"
}

_app_util_check_update() {
  local update
  update=$(curl -s "$CLI_URL")
  [ -z "$update" ] && ui_notify_critical "Failed to fetch update information"
  update="$(printf "%s\n" "$update" | diff -u "$CLI_PATH" -)"
  if [ -n "$update" ]; then
    # TODO: show pretty diffs
    ui_confirm "An update has been found would you like to see the changes before deciding whether to update?" && echo "$update" | ui_pager
    ui_confirm "Would you like to proceed with the update?" && _app_util_update_script
  else
    return 1
  fi
}

_app_edit_config() {
  if command -v "$PREFERRED_EDITOR" >/dev/null 2>&1; then
    $PREFERRED_EDITOR "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "$EDITOR" >/dev/null 2>&1; then
    $EDITOR "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "open" >/dev/null 2>&1; then
    open "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  elif command -v "xdg-open" >/dev/null 2>&1; then
    xdg-open "$CLI_CONFIG_DIR/${CLI_NAME}.conf"
  else
    send_notification "Could not find preferred editor ($PREFERRED_EDITOR) or editor env ($EDITOR) or xdg-open or open" && exit 1
  fi
}

_app_generate_desktop_entry() {
  local entry
  entry="\
[Desktop Entry]
Name=$CLI_NAME
Type=Application
X-Version=$CLI_VERSION
Path=$HOME
Comment=Browse Youtube from the terminal
Terminal=true
Exec=$0
Categories=Education"
  printf "%s" "$entry"
  _util_byebye
}

_app_update_check() {
  local timestamp_file
  local interval
  local current_time
  local last_check_time

  if [ "$CONFIG_CHECK_FOR_UPDATES" = "true" ]; then
    timestamp_file="$CLI_CACHE_DIR/.last_update_check"

    # Time interval in seconds (6 hours = 21600 seconds)
    interval=$((12 * 60 * 60))

    # Determine whether to run the update check
    current_time=$(date +%s)
    last_check_time=$(cat "$timestamp_file" 2>/dev/null || echo 0)

    if [ "$((current_time - last_check_time))" -ge "$interval" ]; then
      _app_util_check_update
      echo "$current_time" >"$timestamp_file"
    fi
  fi
}

_app_core_dep_ch() {
  ! _dep_ch "yt-dlp" >/dev/null 2>&1 && ui_notify_critical "yt-dlp is not installed and is a core dep please install it to proceed"
  ! _dep_ch "jq" && ui_notify_critical "jq is not installed and is a core dep please install it to proceed"
  ! _dep_ch "fzf" && ui_notify_critical "fzf is not installed and is a core dep please install it to proceed"
}

# ==============================================================================
# APP: usage
# ==============================================================================
_app_usage() {
  local help_msg
  help_msg="\
A script written to browse youtube from the terminal

Usage: $CLI_NAME [arguments] [options] 

Commandline options override the config

Options:
  -S, --search [Search Terms]
    search for a video
  -e, --edit-config
    edit $CLI_NAME config file
  --rofi-theme <path>
    set the path to your rofi config file
  --disown-streaming-process
    disown the streaming process so you can contine streaming even if you close $CLI_NAME
  --no-disown-streaming-process
    don't disown the streaming process
  --disown-downloading-process
    disown the downloading process so you can contine streaming even if you close $CLI_NAME
  --no-disown-downloading-process
    don't disown the downloading process
  -s <selector>,--preferred-selector <selector> [fzf/rofi]
    set the preferred selector for $CLI_NAME to use
  -p <player>,--player <player> [mpv/vlc/tplay]
    set the video player for $CLI_NAME to use
  -x <extension>,--extension <extension> [name of extension file at $CLI_EXTENSIONS_DIR or full path]
    set the extension for $CLI_NAME to use (accepts full path starting with /)
  --preview
    enable the preview window
  --no-preview
    disable the preview window
  -E, --generate-desktop-entry
    print the desktop entry and exit
  -h, --help
    Show this help message and exit
  -v, --version
    print the $CLI_NAME version and exit

arguments:
  completions
    generates shell completions for $CLI_NAME

Examples:
  $CLI_NAME --generate-desktop-entry
  $CLI_NAME completions --fish"

  printf "%s\n" "$help_msg"
  exit "${1:-0}"
}

_app_usage_completions() {
  local help_msg
  help_msg="\
Generate shell completions for $CLI_NAME

Options:
  --fish
    print fish completions and exit
  --bash
    print bash completions and exit
  --zsh
    print zsh completions and exit

Example:
  $CLI_NAME completions --fish
  $CLI_NAME completions --bash
  $CLI_NAME completions --zsh"

  printf "%s\n" "$help_msg"
  exit "${1:-0}"
}

# ==============================================================================
# APP: completions
# ==============================================================================
_app_completions_fish() {
  local completions
  completions="\
# --- completions ---
complete -c $CLI_NAME --no-files --arguments \"completions\" --condition 'not __fish_contains_opt sort-by S e edit-config s preferred-selector  E generate-desktop-entry rofi-theme'

complete -c $CLI_NAME --no-files --short-option h --long-option help --description 'Print a short help text and exit'
complete -c $CLI_NAME --no-files --short-option v --long-option version --description 'Print a short version string and exit' --condition 'not __fish_seen_subcommand_from completions'

complete -c $CLI_NAME --no-files --short-option e --long-option edit-config --description 'Edit $CLI_NAME config file' --condition 'not __fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option U --long-option update --description 'update the script' --condition 'not __fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option p --long-option player --description 'the video player to use' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments 'mpv vlc tplay'
complete -c $CLI_NAME --no-files --short-option x --long-option extension --description 'The extension to use' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments \"(command ls $CLI_EXTENSION_DIR)\"
complete -c $CLI_NAME --no-files --short-option s --long-option preferred-selector --description 'your preferred selector' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments 'fzf rofi'
complete -c $CLI_NAME --no-files --short-option E --long-option generate-desktop-entry --description 'generate desktop entry info' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --no-files --long-option preview --description 'enable preview window' --condition 'not __fish_seen_subcommand_from completions' 
complete -c $CLI_NAME --no-files --long-option no-preview --description 'disable preview window' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --force-files --long-option rofi-theme --description 'the path to your rofi config file' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --no-files --short-option S --long-option search --description 'the terms you want to search' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --no-files --short-option z --long-option zsh --description 'print zsh completions' --condition '__fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option b --long-option bash --description 'print bash completions' --condition '__fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option f --long-option fish --description 'print fish completions' --condition '__fish_seen_subcommand_from completions'"
  printf "%s\n" "$completions"
  exit 1
}

# ==============================================================================
# APP:cmdline parser
# ==============================================================================
__app_cmd_line_parser_completions() {
  [ -n "$2" ] || _app_usage 1
  case "$2" in
  -f | --fish) _app_completions_fish ;;
  -b | --bash)
    # TODO: write bash completions
    echo Contribute to "$CLI_NAME" by writing bash completions
    exit 1
    ;;
  -z | --zsh)
    # TODO: write zsh completions
    echo Contribute to "$CLI_NAME" by writing zsh completions
    exit 1
    ;;
  -h | --help) _app_usage_completions ;;
  *) _app_usage_completions 1 ;;
  esac

}

__app_cmd_line_parser_extensions() {
  [ -n "$2" ] || usage 1
  if [ "${2#/}" != "$2" ]; then
    . "$2"
  else
    . "$CLI_EXTENSION_DIR/$2"
  fi
  shift

}

_app_cmd_line_parser() {
  while [ $# -gt 0 ]; do
    case "$1" in
    -h | --help) _app_usage ;;
    -v | --version)
      echo "$CLI_NAME v$CLI_VERSION MIT Copyright © 2024 $CLI_AUTHOR projects"
      exit 0
      ;;
    -e | --edit-config)
      _app_edit_config
      _util_byebye
      ;;
    -U | --update)
      ! _app_util_check_update && ui_notify "No updates found, script is up to date :)" && _util_byebye
      ;;
    -S | --search)
      CMD_ACTION="Search"
      CMD_SEARCH_TERMS="$2"
      shift
      ;;
    -l | --launcher)
      [ -n "$2" ] || _app_usage 1
      CONFIG_LAUNCHER="$2"
      shift
      ;;
    -i | --preview)
      CONFIG_ENABLE_PREVIEW=true
      ;;
    -I | --no-preview)
      CONFIG_ENABLE_PREVIEW=false
      ;;
    --disown-streaming-process)
      CONFIG_DISOWN_STREAMING_PROCESS=true
      ;;
    --no-disown-streaming-process)
      CONFIG_DISOWN_STREAMING_PROCESS=false
      ;;
    --disown-downloading-process)
      CONFIG_DISOWN_DOWNLOADING_PROCESS=true
      ;;
    --no-disown-downloading-process)
      CONFIG_DISOWN_DOWNLOADING_PROCESS=false
      ;;
    --rofi-theme-main)
      [ -n "$2" ] || _app_usage 1
      CONFIG_ROFI_THEME_MAIN="$2"
      shift
      ;;
    --rofi-theme-preview)
      [ -n "$2" ] || _app_usage 1
      CONFIG_ROFI_THEME_PREVIEW="$2"
      shift
      ;;
    --rofi-theme-prompt)
      [ -n "$2" ] || _app_usage 1
      CONFIG_ROFI_THEME_PROMPT="$2"
      shift
      ;;
    --rofi-theme-confirm)
      [ -n "$2" ] || _app_usage 1
      CONFIG_ROFI_THEME_CONFIRM="$2"
      shift
      ;;
    -p | --player)
      [ -n "$2" ] || _app_usage 1
      CONFIG_PLAYER="$2"
      shift
      ;;
    -E | --generate-desktop-entry) _app_generate_desktop_entry ;;
    completions) __app_cmd_line_parser_completions "$@" ;;
    -x | --extensions) __app_cmd_line_parser_extensions "$@" ;;
    *) _app_usage 1 ;;
    esac
    shift
  done
}

# ==============================================================================
# App
# ==============================================================================
main() {
  trap _util_byebye INT TERM
  _init_env
  _load_config
  _app_cmd_line_parser "$@"
  _app_update_check
  _app_core_dep_ch
  _menu_main
}

main "$@"

# MIT License
#
# Copyright (c) 2024-2026 Benexl
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
