#!/usr/bin/env bash
# A script written by Benexl in September 2024 under MIT LICENSE

# ---------------------------------------------
# CLI: General Information
# ---------------------------------------------
CLI_NAME="yt-x"
CLI_VERSION="1.0.0"
CLI_DESCRIPTION="A command-line tool for browsing and streaming YouTube videos using yt-dlp and mpv."
CLI_AUTHOR="Benexl"
CLI_LICENSE="MIT"
CLI_REPO_HOME="https://github.com/benexl/yt-x"

# ---------------------------------------------
# CLI: Environment Constants
# ---------------------------------------------
case "$(uname -a)" in
*ndroid) CLI_PLATFORM="android" ;;
*Darwin*) CLI_PLATFORM="mac" ;;
*MINGW* | *WSL2*) CLI_PLATFORM="windows" ;;
*) CLI_PLATFORM="linux" ;;
esac

# ---------------------------------------------
# CLI: Directories
# ---------------------------------------------
: ${CLI_CONFIG_DIR:="${XDG_CONFIG_HOME:-$HOME/.config}/$CLI_NAME"}
: ${CLI_CUSTOM_PLAYLISTS_DIR:="${XDG_CONFIG_HOME:-$HOME/.config}/$CLI_NAME/custom-playlists"}
: ${CLI_DATA_DIR:="${XDG_DATA_HOME:-$HOME/.local/share}/$CLI_NAME"}
: ${CLI_EXTENSIONS_DIR:="$CLI_DATA_DIR/extensions"}
: ${CLI_DEFAULT_EXTENSION_DIR:="$CLI_EXTENSIONS_DIR/DEFAULT"}
: ${CLI_CACHE_DIR:="${XDG_CACHE_HOME:-$HOME/.cache}/$CLI_NAME"}
: ${CLI_LOG_DIR:="$CLI_DATA_DIR/logs"}
: ${CLI_TEMP_DIR:="/tmp/$CLI_NAME"}
: ${CLI_PREVIEW_IMAGES_CACHE_DIR:="${CLI_CACHE_DIR}/preview-images"}
: ${CLI_PREVIEW_SCRIPTS_CACHE_DIR:="${CLI_CACHE_DIR}/preview-scripts"}
: ${CLI_MIXES_CACHE_DIR:="${CLI_CACHE_DIR}/mixes"}

# Create necessary directories if they don't exist
[ ! -d "$CLI_CONFIG_DIR" ] && mkdir -p "$CLI_CONFIG_DIR"
[ ! -d "$CLI_CUSTOM_PLAYLISTS_DIR" ] && mkdir -p "$CLI_CUSTOM_PLAYLISTS_DIR"
[ ! -d "$CLI_EXTENSIONS_DIR" ] && mkdir -p "$CLI_EXTENSIONS_DIR"
[ ! -d "$CLI_DEFAULT_EXTENSION_DIR" ] && mkdir -p "$CLI_DEFAULT_EXTENSION_DIR"
[ ! -d "$CLI_CACHE_DIR" ] && mkdir -p "$CLI_CACHE_DIR"
[ ! -d "$CLI_PREVIEW_IMAGES_CACHE_DIR" ] && mkdir -p "$CLI_PREVIEW_IMAGES_CACHE_DIR"
[ ! -d "$CLI_PREVIEW_SCRIPTS_DIR" ] && mkdir -p "$CLI_PREVIEW_SCRIPTS_DIR"
[ ! -d "$CLI_RUNTIME_PLAYLISTS_CACHE_DIR" ] && mkdir -p "$CLI_RUNTIME_PLAYLISTS_CACHE_DIR"
[ ! -d "$CLI_TEMP_DIR" ] && mkdir -p "$CLI_TEMP_DIR"
[ ! -d "$CLI_LOG_DIR" ] && mkdir -p "$CLI_LOG_DIR"

# ---------------------------------------------
# CLI: Files
# ---------------------------------------------
CLI_CONFIG_FILE="$CLI_CONFIG_DIR/$CLI_NAME.conf"
CLI_RECENT_FILE="$CLI_CONFIG_DIR/recent.json"
CLI_SEARCH_HISTORY_FILE="$CLI_CONFIG_DIR/search-history"
CLI_EXTENSIONS_INDEX_FILE="$CLI_CONFIG_DIR/extensions.json"
CLI_LOG_FILE="$CLI_LOG_DIR/$CLI_NAME.log"
CLI_UPDATE_CHECK_FILE="$CLI_CACHE_DIR/.last-update-check"

# ---------------------------------------------
# CLI: Other Constants
# ---------------------------------------------
CLI_ASCII_ART="\
██╗░░░██╗████████╗░░░░░░██╗░░██╗
╚██╗░██╔╝╚══██╔══╝░░░░░░╚██╗██╔╝
░╚████╔╝░░░░██║░░░█████╗░╚███╔╝░
░░╚██╔╝░░░░░██║░░░╚════╝░██╔██╗░
░░░██║░░░░░░██║░░░░░░░░░██╔╝╚██╗
░░░╚═╝░░░░░░╚═╝░░░░░░░░░╚═╝░░╚═╝
"
CLI_INFO="info"
CLI_SUCCESS="success"
CLI_WARNING="warning"
CLI_ERROR="error"

# ---------------------------------------------
# COLORS
# ---------------------------------------------
if [ $COLOR_TERM = "truecolor" ] || [ $COLORTERM = "24bit" ]; then
	COLOR_RED="\e[38;2;255;0;0m"
	COLOR_GREEN="\e[38;2;0;255;0m"
	COLOR_YELLOW="\e[38;2;255;255;0m"
	COLOR_BLUE="\e[38;2;0;0;255m"
	COLOR_RESET="\e[0m"
else
	COLOR_RED="\e[31m"
	COLOR_GREEN="\e[32m"
	COLOR_YELLOW="\e[33m"
	COLOR_BLUE="\e[34m"
	COLOR_RESET="\e[0m"
fi

# ---------------------------------------------
# DEFAULT CONFIGURATION VALUES
# ---------------------------------------------
_CONFIG_AUTO_LOADED_EXTENSIONS=""
_CONFIG_PRETTY_PRINT="true"
_CONFIG_SELECTOR="fzf"
_CONFIG_VIDEO_QUALITY="best"
_CONFIG_PREVIEW="none"
_CONFIG_DISOWN_STREAMING_PROCESS="false"
_CONFIG_UPDATE_RECENT="true"
_CONFIG_SEARCH_HISTORY="true"
_CONFIG_NO_OF_RECENT=25
_CONFIG_PLAYER="mpv"
_CONFIG_BROWSER=""
_CONFIG_NO_OF_SEARCH_RESULTS=5
_CONFIG_NOTIFICATION_DURATION=5
_CONFIG_DOWNLOADS_DIR="${XDG_VIDEOS_DIR:-"$HOME/Videos"}/$CLI_NAME"
_CONFIG_UPDATE_CHECK="true"
_CONFIG_FZF_OPTS='
    --color=fg:#d0d0d0,fg+:#d0d0d0,bg:#121212,bg+:#262626
    --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
    --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
    --color=border:#262626,label:#aeaeae,query:#d9d9d9
    --border="rounded" --border-label="" --preview-window="border-rounded" --prompt="> "
    --marker=">" --pointer="◆" --separator="─" --scrollbar="│"
'
_CONFIG_ROFI_THEME_MAIN="https://raw.githubusercontent.com/Benexl/yt-x/refs/heads/v1.0.0/assets/defaults/rofi-themes/main.rasi"
_CONFIG_ROFI_THEME_PREVIEW="https://raw.githubusercontent.com/Benexl/yt-x/refs/heads/v1.0.0/assets/defaults/rofi-themes/preview.rasi"
_CONFIG_ROFI_THEME_PROMPT="https://raw.githubusercontent.com/Benexl/yt-x/refs/heads/v1.0.0/assets/defaults/rofi-themes/prompt.rasi"
_CONFIG_ROFI_THEME_CONFIRM="https://raw.githubusercontent.com/Benexl/yt-x/refs/heads/v1.0.0/assets/defaults/rofi-themes/confirm.rasi"

# environment dependant
_CONFIG_EDITOR="${EDITOR:-"vim"}"
_CONFIG_IMAGE_RENDERER=""
command -v viu >/dev/null 2>&1 && _CONFIG_IMAGE_RENDERER="viu"
command -v chafa >/dev/null 2>&1 && _CONFIG_IMAGE_RENDERER="chafa"
command -v icat >/dev/null 2>&1 && _CONFIG_IMAGE_RENDERER="icat"