#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

# ==============================================================================
# Main Loop Override
# ==============================================================================
_menu_main() {
  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    local type
    local video
    local prev_dir

    # 1. Select Type
    type=$(printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" | ui_launcher "Select the type of file to play")

    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    video=$(
      printf "%s\n%s" "$(find "$CONFIG_DOWNLOAD_DIR/$type" -type f 2>/dev/null | sed "s|^$CONFIG_DOWNLOAD_DIR/$type/||")" "$TXT_MENU_BACK" |
        ui_launcher "Select the video"
    )

    case "$video" in
    "$TXT_MENU_BACK" | "") continue ;;
    esac

    # 3. Play the selected video
    play "$CONFIG_DOWNLOAD_DIR/$type/$video"

    # 4. Loop continuation
    ui_confirm "Do you want to play another video?" || _util_byebye
  done
}
