blank_issues_enabled: false
contact_links:
  - name: Read the FAQ
    url: https://github.com/Benexl/yt-x#%E2%9D%93-frequently-asked-questions-faq
    about: Please read the FAQ before asking a question or opening an issue!
