#!/bin/sh
# shellcheck disable=SC2034
# ==============================================================================
# yt-x Theme Extension: Catppuchin Mocha
# ==============================================================================

if $CLI_SUPPORTS_TRUE_COLOR && $CONFIG_ENABLE_COLORS; then
  # Catppuchin Mocha: Mauve (#cba6f7)
  THEME_FZF_ICON_COLOR_PRIMARY="$(printf '\033[38;2;203;166;247m')"

  # Catppuchin Mocha: Overlay1 (#7f849c)
  THEME_FZF_ICON_COLOR_SECONDARY="$(printf '\033[38;2;127;132;156m')"

  # Catppuchin Mocha: Peach (#fab387)
  THEME_FZF_ICON_COLOR_ACCENT="$(printf '\033[38;2;250;179;135m')"

  # Catppuchin Mocha: Red (#f38ba8)
  THEME_FZF_ICON_COLOR_ERROR="$(printf '\033[38;2;243;139;168m')"

  # Catppuccin Mocha: Text (#cdd6f4)
  THEME_FZF_PREVIEW_TITLE="$(printf '\033[38;2;205;214;244m')"

  # Catppuchin Mocha: Blue (#89b4fa)
  THEME_FZF_PREVIEW_KEY="$(printf '\033[38;2;137;180;250m')"

  # Catppuccin Mocha: Surface2 (#585b70)
  THEME_FZF_PREVIEW_VALUE="$(printf '\033[38;2;88;91;112m')"

  # Catppuchin Mocha: Surface2 (#585b70)
  THEME_FZF_PREVIEW_DIVIDER="$(printf '\033[38;2;88;91;112m')"

  # Catppuchin Mocha: Green (#a6e3a1)
  THEME_PLAYER_START="$(printf '\033[38;2;166;227;161m')"

  THEME_BOLD="$(printf '\033[1m')"
  THEME_RESET="$(printf '\033[0m')"

CONFIG_FZF_OPTS="
--color=bg+:#313244
--color=bg:#1e1e2e
--color=border:#89b4fe
--color=fg:#cdd6f4
--color=gutter:#1e1e2e
--color=header:#89b4fe
--color=hl+:#cba6f7
--color=hl:#cba6f7
--color=info:#6c7086
--color=marker:#f5c2e7
--color=pointer:#f5c2e7
--color=prompt:#cba6f7
--color=query:#cdd6f4:regular
--color=scrollbar:#6c7086
--color=separator:#f9e2af
--color=spinner:#f5c2e7"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $CONFIG_FZF_OPTS"
fi
