#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

CLI_LOCAL_PREVIEW_DIR="$CLI_PREVIEW_DIR/local"
CLI_LOCAL_PREVIEW_SCRIPTS_DIR="$CLI_LOCAL_PREVIEW_DIR/scripts"
CLI_LOCAL_PREVIEW_IMGS_DIR="$CLI_LOCAL_PREVIEW_DIR/imgs"
mkdir -p "$CLI_LOCAL_PREVIEW_SCRIPTS_DIR" "$CLI_LOCAL_PREVIEW_IMGS_DIR"

_handle_action() {
  local action

  action=$(printf "Media\nPlaylist\nChannel\n%s" "$TXT_MENU_BACK" | ui_launcher "Select what to view")

  case "$action" in
  Media)
    play "$CONFIG_DOWNLOAD_DIR/$type/$playlist/$channel/$media"
    ;;
  Channel)
    play "$CONFIG_DOWNLOAD_DIR/$type/$playlist/$channel"
    ;;
  Playlist)
    play "$CONFIG_DOWNLOAD_DIR/$type/$playlist"
    ;;
  "$TXT_MENU_BACK" | "")
    return 1
    ;;
  esac
}

_menu_main() {
  local base_dir type playlist channel media

  [ "$CONFIG_ENABLE_PREVIEW" = "true" ] && __preview_fzf_create_shared_script

  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    type=$(
      printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" |
        _preview_local |
        ui_launcher_with_preview "Select the type of file to play"
    )
    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    base_dir="$CONFIG_DOWNLOAD_DIR/$type"
    playlist=$(
      printf "%s\n%s" "$(command ls "$base_dir" 2>/dev/null)" "$TXT_MENU_BACK" |
        _preview_local "$base_dir" |
        ui_launcher_with_preview "Select the playlist to play"
    )
    case "$playlist" in
    "$TXT_MENU_BACK" | "") continue ;;
    esac

    base_dir="$CONFIG_DOWNLOAD_DIR/$type/$playlist"
    channel=$(
      printf "%s\n%s" "$(command ls "$base_dir" 2>/dev/null)" "$TXT_MENU_BACK" |
        _preview_local "$base_dir" |
        ui_launcher_with_preview "Select the channel to play"
    )
    case "$channel" in
    "$TXT_MENU_BACK" | "") continue ;;
    esac

    base_dir="$CONFIG_DOWNLOAD_DIR/$type/$playlist/$channel"
    media=$(
      printf "%s\n%s" "$(command ls "$base_dir" 2>/dev/null)" "$TXT_MENU_BACK" |
        _preview_local "$base_dir" |
        ui_launcher_with_preview "Select the video to play"
    )
    case "$media" in
    "$TXT_MENU_BACK" | "") continue ;;
    esac

    _handle_action || continue

    ui_confirm "Do you want to play another video?" || _util_byebye
  done
}
