#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

# shellcheck disable=SC1091
. "$CLI_EXTENSIONS_DIR/cmds/downloads/shared"

CLI_LOCAL_AUTO_GEN_PLAYLISTS="$CLI_AUTO_GEN_PLAYLISTS/local"
mkdir -p "$CLI_LOCAL_AUTO_GEN_PLAYLISTS"

_menu_main() {
  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    local base_dir type channel temp_playlist

    type=$(
      printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" |
        _preview_local |
        ui_launcher_with_preview "Select the type of file to play"
    )

    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    base_dir="$CONFIG_DOWNLOAD_DIR/$type"
    channel=$(
      printf "%s\n%s" "$(command ls "$base_dir" 2>/dev/null)" "$TXT_MENU_BACK" |
        _preview_local "$base_dir" |
        ui_launcher_with_preview "Select the playlist to play"
    )

    case "$channel" in
    "$TXT_MENU_BACK" | "") continue ;;
    esac

    temp_playlist="$CLI_LOCAL_AUTO_GEN_PLAYLISTS/$(_util_generate_hash "$type/$channel").m3u8"
    echo "#EXTM3U" >"$temp_playlist"

    find "$base_dir/$channel" -type f 2>/dev/null >>"$temp_playlist"

    if [ "$(wc -l <"$temp_playlist")" -gt 1 ]; then
      play "$temp_playlist"
    else
      ui_notify_warning "No media found in selected directory!"
    fi

    ui_confirm "Do you want to play another channel?" || _util_byebye
  done
}
