#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

# shellcheck disable=SC1091
. "$CLI_EXTENSIONS_DIR/cmds/downloads/shared"

_menu_main() {
  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    local base_dir
    local type
    local playlist

    type=$(
      printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" |
        _preview_local |
        ui_launcher_with_preview "Select the type of file to play"
    )

    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    base_dir="$CONFIG_DOWNLOAD_DIR/$type"
    playlist=$(
      printf "%s\n%s" "$(command ls "$base_dir" 2>/dev/null)" "$TXT_MENU_BACK" |
        _preview_local "$base_dir" |
        ui_launcher_with_preview "Select the playlist to play"
    )

    case "$playlist" in
    "$TXT_MENU_BACK" | "") continue ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    esac

    play "$CONFIG_DOWNLOAD_DIR/$type/$playlist"

    ui_confirm "Do you want to play another playlist?" || _util_byebye
  done
}
