#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

# shellcheck disable=SC1091
. "$CLI_EXTENSIONS_DIR/cmds/downloads/shared"

_menu_main() {
  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    local type
    local video

    type=$(
      printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" |
        _preview_local |
        ui_launcher_with_preview "Select the type of file to play"
    )

    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    video=$(
      printf "%s\n%s" "$(find "$CONFIG_DOWNLOAD_DIR/$type" -type f 2>/dev/null | sed "s|^$CONFIG_DOWNLOAD_DIR/$type/||")" "$TXT_MENU_BACK" |
        _preview_local "$CONFIG_DOWNLOAD_DIR/$type" |
        ui_launcher_with_preview "Select the video"
    )

    case "$video" in
    "$TXT_MENU_BACK" | "") continue ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    esac

    play "$CONFIG_DOWNLOAD_DIR/$type/$video"

    ui_confirm "Do you want to play another video?" || _util_byebye
  done
}
